import type { Q } from './math-drill-questions-types';

// CasePad math-drill pool — 100+ case-math problems sequenced beginner → expert
// across consulting, IB/PE/VC, PM, and marketing tracks.
//
// Calibration notes for future authors:
//  - L1 tolerance ~ 0–2: exact mental arithmetic, no estimation
//  - L2 tolerance ~ 2–10% of answer: structured shortcuts, mild rounding
//  - L3 tolerance ~ 5–10%: discounting + perpetuities — round at each step
//  - L4 tolerance ~ 10–15%: paper-LBO / Fermi estimation — directional only
//
// Order within a level is roughly easy → hard, so a student can drill linearly
// instead of randomising and still get a sensible difficulty ramp.

export const MATH_DRILL_POOL: Q[] = [
  // ────────────────────────────────────────────────────────────────────
  // LEVEL 1 — beginner (25 questions)
  // %, growth rates, multiplication shortcuts, division, fractions, ratios
  // ────────────────────────────────────────────────────────────────────

  {
    level: 1, track: 'all', topic: 'Percentage',
    question: '15% of 480 = ?',
    answer: 72, tolerance: 1,
    explanation: '10% of 480 = 48; half of that (5%) = 24; sum = 72.',
    common_trap: 'Computing only 10% (48) and forgetting to add the 5%.',
  },
  {
    level: 1, track: 'consulting', topic: 'Percentage',
    question: 'A retailer marks up cost ₹250 by 40%. Selling price?',
    answer: 350, tolerance: 1,
    explanation: 'Markup = 40% of 250 = 100. SP = 250 + 100 = 350.',
    common_trap: 'Treating 40% as the margin on SP instead of markup on cost.',
  },
  {
    level: 1, track: 'all', topic: 'Percentage',
    question: '8% of 1,250 = ?',
    answer: 100, tolerance: 1,
    explanation: '1% of 1250 = 12.5, × 8 = 100. Or: 8/100 × 1250 = 100.',
    common_trap: 'Mis-shifting the decimal — answering 10 or 1000.',
  },
  {
    level: 1, track: 'marketing', topic: 'Percentage',
    question: 'Of 9,000 site visits, 270 convert. Conversion %?',
    answer: 3, tolerance: 0,
    explanation: '270 / 9000 = 27 / 900 = 3/100 = 3%.',
    common_trap: 'Inverting the ratio (9000 / 270) and reporting 33.',
  },
  {
    level: 1, track: 'all', topic: 'Growth rate',
    question: 'Revenue went 80 → 100. Growth %?',
    answer: 25, tolerance: 0,
    explanation: 'Δ / base = 20 / 80 = 1/4 = 25%.',
    common_trap: 'Dividing by the new value (20/100 = 20%). Always divide by the *old* base.',
  },
  {
    level: 1, track: 'consulting', topic: 'Growth rate',
    question: 'EBITDA fell 60 → 45. % decline?',
    answer: 25, tolerance: 1,
    explanation: 'Drop of 15 on a base of 60 = 15/60 = 25%.',
    common_trap: 'Reporting the absolute drop (15) instead of the percent.',
  },
  {
    level: 1, track: 'pm', topic: 'Growth rate',
    question: 'DAU grew 1.2M → 1.5M month over month. MoM growth %?',
    answer: 25, tolerance: 1,
    explanation: '0.3M / 1.2M = 1/4 = 25%.',
    common_trap: 'Reporting 30% by mistakenly using the new base 1.5M.',
  },
  {
    level: 1, track: 'ib_pe_vc', topic: 'Growth rate',
    question: 'Stock fell from $80 to $60. % decline?',
    answer: 25, tolerance: 0,
    explanation: 'Δ / base = 20 / 80 = 25%.',
    common_trap: 'Saying 33% — which is the gain needed to recover, not the loss.',
  },
  {
    level: 1, track: 'all', topic: 'Multiplication',
    question: '23 × 17 = ?',
    answer: 391, tolerance: 0,
    explanation: '(20 × 17) + (3 × 17) = 340 + 51 = 391.',
    common_trap: 'Forgetting the carry on 3 × 7 and answering 381.',
  },
  {
    level: 1, track: 'all', topic: 'Multiplication',
    question: '47 × 38 = ? (within 100)',
    answer: 1786, tolerance: 100,
    explanation: 'Round: 50 × 38 = 1900; subtract 3 × 38 (≈114) → ~1786.',
    common_trap: 'Skipping the correction step after rounding 47 → 50.',
  },
  {
    level: 1, track: 'consulting', topic: 'Multiplication',
    question: '125 × 80 = ?',
    answer: 10000, tolerance: 0,
    explanation: '125 × 8 = 1000, × 10 = 10,000. (125 = 1000/8 trick.)',
    common_trap: 'Long-multiplying and dropping a zero, getting 1,000.',
  },
  {
    level: 1, track: 'pm', topic: 'Multiplication',
    question: '0.4% of 25M users churn. How many users? (in thousands)',
    answer: 100, tolerance: 1,
    explanation: '0.4% = 0.004; × 25M = 100,000 = 100K.',
    common_trap: 'Reading 0.4% as 4% and getting 1,000K.',
  },
  {
    level: 1, track: 'all', topic: 'Division',
    question: '4,500 / 35 = ? (round to nearest integer)',
    answer: 129, tolerance: 1,
    explanation: '35 × 100 = 3500; remaining 1000 / 35 ≈ 28.6; total ≈ 128.6 → 129.',
    common_trap: 'Estimating with 4500/30 = 150 without correcting downward.',
  },
  {
    level: 1, track: 'ib_pe_vc', topic: 'Division',
    question: 'Net income $84M; 12M shares outstanding. EPS ($)?',
    answer: 7, tolerance: 0,
    explanation: '84 / 12 = 7. Pure cancellation.',
    common_trap: 'Mixing up numerator/denominator (12/84) under time pressure.',
  },
  {
    level: 1, track: 'consulting', topic: 'Division',
    question: 'Plant produced 13,200 units in 22 days. Units/day?',
    answer: 600, tolerance: 0,
    explanation: '13200 / 22: 22 × 600 = 13200 exactly.',
    common_trap: 'Estimating as 13000/20 = 650 and skipping the cleanup.',
  },
  {
    level: 1, track: 'all', topic: 'Fractions',
    question: '3/8 of 240 = ?',
    answer: 90, tolerance: 0,
    explanation: '240 / 8 = 30; × 3 = 90.',
    common_trap: 'Multiplying first (240 × 3 = 720) and forgetting to divide.',
  },
  {
    level: 1, track: 'marketing', topic: 'Fractions',
    question: '2/5 of a 50,000-strong audience clicked the ad. Clicks?',
    answer: 20000, tolerance: 0,
    explanation: '1/5 of 50,000 = 10,000; × 2 = 20,000.',
    common_trap: 'Computing 5/2 of 50K = 125K — flipping the fraction.',
  },
  {
    level: 1, track: 'all', topic: 'Fractions',
    question: '1/3 + 1/4 = ? (as a decimal, 2 dp)',
    answer: 0.58, tolerance: 0.02,
    explanation: 'LCD 12: 4/12 + 3/12 = 7/12 ≈ 0.583.',
    common_trap: 'Adding 1/3 + 1/4 = 2/7 — illegal across denominators.',
  },
  {
    level: 1, track: 'consulting', topic: 'Ratio',
    question: 'Revenue split India:US = 3:5, total ₹240Cr. India revenue (₹Cr)?',
    answer: 90, tolerance: 0,
    explanation: '3+5 = 8 parts; 240/8 = 30/part; India = 3 × 30 = 90.',
    common_trap: 'Treating 3:5 as 3/5 of total (would give 144).',
  },
  {
    level: 1, track: 'pm', topic: 'Ratio',
    question: 'Free:paid users = 9:1; 200K paid. How many free (in K)?',
    answer: 1800, tolerance: 0,
    explanation: 'Free = 9 × paid = 9 × 200K = 1800K.',
    common_trap: 'Computing total (1800K + 200K) and reporting 2000.',
  },
  {
    level: 1, track: 'all', topic: 'Percentage',
    question: '125% of 80 = ?',
    answer: 100, tolerance: 0,
    explanation: '100% of 80 = 80; +25% of 80 (= 20) → 100.',
    common_trap: 'Subtracting instead of adding for "more than 100".',
  },
  {
    level: 1, track: 'marketing', topic: 'Growth rate',
    question: 'CAC up from ₹400 to ₹500. % increase?',
    answer: 25, tolerance: 0,
    explanation: 'Δ 100 on base 400 = 25%.',
    common_trap: 'Dividing by 500 (new) and getting 20%.',
  },
  {
    level: 1, track: 'ib_pe_vc', topic: 'Multiplication',
    question: '15 × 12 × 6 = ?',
    answer: 1080, tolerance: 0,
    explanation: '15 × 12 = 180; × 6 = 1080.',
    common_trap: 'Multiplying out of order under stress and dropping a factor.',
  },
  {
    level: 1, track: 'all', topic: 'Percentage',
    question: 'A bill of ₹2,400 includes 18% GST. Pre-tax amount?',
    answer: 2034, tolerance: 5,
    explanation: 'Pre-tax × 1.18 = 2400 → pre-tax = 2400/1.18 ≈ 2034.',
    common_trap: 'Subtracting 18% of 2400 (= 432) from 2400 → 1968 (wrong direction).',
  },
  {
    level: 1, track: 'consulting', topic: 'Percentage',
    question: 'Costs are 60% of revenue. If revenue is ₹50Cr, profit (₹Cr)?',
    answer: 20, tolerance: 0,
    explanation: 'Margin = 40%; 0.4 × 50 = 20.',
    common_trap: 'Computing costs (30) and reporting that as profit.',
  },

  // ────────────────────────────────────────────────────────────────────
  // LEVEL 2 — core (25 questions)
  // CAGR, breakeven, contribution margin, payback, sizing, conversion,
  // retention, basic CAC/LTV
  // ────────────────────────────────────────────────────────────────────

  {
    level: 2, track: 'ib_pe_vc', topic: 'CAGR',
    question: '$100 → $200 in 9 years. CAGR %?',
    answer: 8, tolerance: 1,
    explanation: 'Rule of 72: 72/9 ≈ 8% to double.',
    common_trap: 'Computing simple growth (100/9 = 11%) instead of compound.',
  },
  {
    level: 2, track: 'ib_pe_vc', topic: 'CAGR',
    question: '$50 → $150 in 5 yr. CAGR %?',
    answer: 25, tolerance: 2,
    explanation: '3× in 5yr ≈ 1.25^5 ≈ 3.05; ~25%.',
    common_trap: 'Using rule of 72 (which only handles doubling, not tripling).',
  },
  {
    level: 2, track: 'consulting', topic: 'CAGR',
    question: 'Revenue ₹400Cr → ₹800Cr in 6 yr. CAGR %?',
    answer: 12, tolerance: 1,
    explanation: 'Doubled in 6 yr; 72/6 = 12%.',
    common_trap: 'Computing average growth (100% / 6 ≈ 17%) instead of compound.',
  },
  {
    level: 2, track: 'consulting', topic: 'Breakeven',
    question: 'FC=$1M, P=$100, VC=$60. Breakeven units?',
    answer: 25000, tolerance: 0,
    explanation: 'CM = $40; FC/CM = 1,000,000 / 40 = 25,000.',
    common_trap: 'Dividing FC by price instead of contribution margin.',
  },
  {
    level: 2, track: 'consulting', topic: 'Breakeven',
    question: 'New SaaS: FC ₹2.4Cr/yr, ARPU ₹2,000/yr, gross margin 80%. Breakeven users?',
    answer: 15000, tolerance: 200,
    explanation: 'Per-user CM = 0.8 × 2000 = 1600; 2.4Cr / 1600 = 24,000,000 / 1600 = 15,000.',
    common_trap: 'Using ARPU directly instead of gross-margin-adjusted contribution.',
  },
  {
    level: 2, track: 'consulting', topic: 'Contribution margin',
    question: 'Price $200, VC $140. CM %?',
    answer: 30, tolerance: 0,
    explanation: 'CM = 60; 60/200 = 30%.',
    common_trap: 'Using VC/Price (70%) instead of (P − VC)/P.',
  },
  {
    level: 2, track: 'pm', topic: 'Contribution margin',
    question: 'Subscription ₹499/mo; servicing cost ₹100/mo. CM %?',
    answer: 80, tolerance: 1,
    explanation: 'CM = 399 / 499 ≈ 80%.',
    common_trap: 'Computing 499/100 = 5x markup and reporting 500%.',
  },
  {
    level: 2, track: 'consulting', topic: 'Payback',
    question: 'Invest $10M, $2.5M/yr cash. Payback (years)?',
    answer: 4, tolerance: 0,
    explanation: '10 / 2.5 = 4. Simple cash-payback ignores discounting.',
    common_trap: 'Discounting the cashflows when payback is undiscounted by definition.',
  },
  {
    level: 2, track: 'marketing', topic: 'Payback',
    question: 'CAC ₹3,000; gross profit ₹500/mo. Payback (months)?',
    answer: 6, tolerance: 0,
    explanation: '3000 / 500 = 6.',
    common_trap: 'Using ARPU (revenue) instead of gross profit per month.',
  },
  {
    level: 2, track: 'consulting', topic: 'Market sizing',
    question: 'India 1.4B × 8% adopters × 100 cups/yr × ₹100. Market size (₹Cr)?',
    answer: 11200, tolerance: 200,
    explanation: '1.4B × 8% = 112M users × 100 cups × ₹100 = ₹1.12Lakh Cr ≈ 11,200 ₹Cr if we mean 100M-scale segments. (Sanity-check unit: 112M × 10K = 11.2K Cr.)',
    common_trap: 'Mixing crore vs lakh while collapsing units.',
  },
  {
    level: 2, track: 'consulting', topic: 'Market sizing',
    question: 'Top-down: Indian shampoo TAM ₹40,000Cr; premium = 15%. Premium TAM (₹Cr)?',
    answer: 6000, tolerance: 100,
    explanation: '15% of 40,000 = 6,000.',
    common_trap: 'Forgetting to convert percent (using 0.15 vs 15) and reporting 600.',
  },
  {
    level: 2, track: 'consulting', topic: 'Market sizing',
    question: 'Bottom-up: 60M Indian households × 30% own a car × ₹4,000/yr on tyres. TAM (₹Cr)?',
    answer: 7200, tolerance: 200,
    explanation: '60M × 30% = 18M cars; × ₹4000 = ₹7,200Cr.',
    common_trap: 'Reporting in ₹Lakh and being off by 100×.',
  },
  {
    level: 2, track: 'pm', topic: 'Conversion',
    question: 'Funnel: 1M visit → 200K sign up → 50K activate → 10K pay. Visit-to-pay %?',
    answer: 1, tolerance: 0,
    explanation: '10K / 1M = 1%.',
    common_trap: 'Multiplying step rates (20% × 25% × 20% = 1%) — same answer, but easy to drop a step.',
  },
  {
    level: 2, track: 'pm', topic: 'Conversion',
    question: 'Step conversions 40%, 50%, 30%. End-to-end conversion %?',
    answer: 6, tolerance: 0,
    explanation: '0.4 × 0.5 × 0.3 = 0.06 = 6%.',
    common_trap: 'Adding (40+50+30 = 120%) — funnels multiply, not add.',
  },
  {
    level: 2, track: 'pm', topic: 'Retention',
    question: 'Day 1 retention 60%, day 7 retention 40%. Day-1-to-day-7 drop %?',
    answer: 33, tolerance: 1,
    explanation: 'Drop = (60-40)/60 = 1/3 ≈ 33%.',
    common_trap: 'Reporting absolute drop (20pp) as a percent.',
  },
  {
    level: 2, track: 'pm', topic: 'Retention curve',
    question: 'Monthly retention 90%; what % of cohort remains after 6 months?',
    answer: 53, tolerance: 2,
    explanation: '0.9^6 ≈ 0.531 = ~53%.',
    common_trap: 'Computing 90% × 6 = 540% (additive nonsense) or 90 - 6×10 = 30.',
  },
  {
    level: 2, track: 'marketing', topic: 'CAC/LTV (basic)',
    question: 'ARPU ₹500/mo; gross margin 60%; avg lifetime 24 mo. LTV (₹)?',
    answer: 7200, tolerance: 100,
    explanation: 'LTV = 500 × 0.6 × 24 = 300 × 24 = 7,200.',
    common_trap: 'Using revenue (500 × 24 = 12,000) instead of gross-margin-adjusted contribution.',
  },
  {
    level: 2, track: 'marketing', topic: 'CAC/LTV (basic)',
    question: 'LTV ₹9,000; CAC ₹3,000. LTV:CAC ratio?',
    answer: 3, tolerance: 0,
    explanation: '9000/3000 = 3. Healthy >3, danger <1.',
    common_trap: 'Inverting ratio (CAC/LTV = 0.33).',
  },
  {
    level: 2, track: 'marketing', topic: 'CAC',
    question: 'Spent ₹15Lakh on ads, acquired 1,500 customers. CAC?',
    answer: 1000, tolerance: 0,
    explanation: '15,00,000 / 1,500 = 1,000.',
    common_trap: 'Lakh ↔ crore confusion (off by 100×).',
  },
  {
    level: 2, track: 'consulting', topic: 'Market share',
    question: 'Brand sells ₹240Cr in a ₹2,000Cr category. Market share %?',
    answer: 12, tolerance: 0,
    explanation: '240/2000 = 12%.',
    common_trap: 'Inverting (2000/240 ≈ 8x) and reporting 8%.',
  },
  {
    level: 2, track: 'ib_pe_vc', topic: 'Margins',
    question: 'Revenue $500M, COGS $300M, OpEx $120M. Operating margin %?',
    answer: 16, tolerance: 1,
    explanation: 'Op profit = 500-300-120 = 80; 80/500 = 16%.',
    common_trap: 'Forgetting OpEx and reporting gross margin (40%).',
  },
  {
    level: 2, track: 'ib_pe_vc', topic: 'EV/EBITDA',
    question: 'EBITDA $40M; sector trades at 8× EV/EBITDA. Implied EV ($M)?',
    answer: 320, tolerance: 0,
    explanation: '40 × 8 = 320.',
    common_trap: 'Dividing instead of multiplying (40/8 = 5).',
  },
  {
    level: 2, track: 'consulting', topic: 'Mix shift',
    question: 'Premium 30% × ₹1000 + Mass 70% × ₹400. Blended ARPU?',
    answer: 580, tolerance: 5,
    explanation: '0.3×1000 + 0.7×400 = 300 + 280 = 580.',
    common_trap: 'Simple average ((1000+400)/2 = 700) ignoring the mix weighting.',
  },
  {
    level: 2, track: 'pm', topic: 'Engagement',
    question: 'DAU = 4M, MAU = 20M. DAU/MAU ratio?',
    answer: 0.2, tolerance: 0.01,
    explanation: '4/20 = 0.2 = 20%. Below 0.2 is "weak product".',
    common_trap: 'Reporting 5× (the inverse).',
  },
  {
    level: 2, track: 'all', topic: 'Compounding',
    question: '12% annual growth for 6 years. Total growth multiple?',
    answer: 1.97, tolerance: 0.1,
    explanation: '1.12^6: rule of 72 says doubling at ~6yr → ≈ 2×.',
    common_trap: 'Adding (12 × 6 = 72%) and reporting 1.72×.',
  },

  // ────────────────────────────────────────────────────────────────────
  // LEVEL 3 — advanced (25 questions)
  // NPV, WACC, terminal value, elasticity, op leverage, full LTV w/ churn,
  // MROI, statistical significance, cohort retention
  // ────────────────────────────────────────────────────────────────────

  {
    level: 3, track: 'ib_pe_vc', topic: 'NPV',
    question: '$2M/yr for 5 yr at 10% discount. PV ($M)?',
    answer: 7.58, tolerance: 0.3,
    explanation: 'Annuity factor at 10%/5yr ≈ 3.79; × 2 ≈ 7.58.',
    common_trap: 'Forgetting the annuity factor and reporting nominal sum (10).',
  },
  {
    level: 3, track: 'ib_pe_vc', topic: 'NPV',
    question: '$5M one-shot in year 5 at 12% discount. PV ($M)?',
    answer: 2.84, tolerance: 0.3,
    explanation: '1.12^5 ≈ 1.76; 5/1.76 ≈ 2.84.',
    common_trap: 'Discounting only one year (5/1.12 = 4.46).',
  },
  {
    level: 3, track: 'ib_pe_vc', topic: 'NPV',
    question: 'Year 1: $10M, Year 2: $20M, Year 3: $30M cashflows at 10%. PV ($M)?',
    answer: 48.16, tolerance: 1,
    explanation: '10/1.1 + 20/1.21 + 30/1.331 ≈ 9.09 + 16.53 + 22.54 ≈ 48.2.',
    common_trap: 'Nominal sum ($60M) without discounting.',
  },
  {
    level: 3, track: 'ib_pe_vc', topic: 'WACC',
    question: '70% equity at 12%, 30% debt at 6% (tax 30%). WACC %?',
    answer: 9.66, tolerance: 0.3,
    explanation: '0.7 × 12 + 0.3 × 6 × 0.7 = 8.4 + 1.26 = 9.66.',
    common_trap: 'Forgetting the (1-t) factor on cost of debt.',
  },
  {
    level: 3, track: 'ib_pe_vc', topic: 'WACC',
    question: '60% equity at 14%, 40% debt at 8% (tax 25%). WACC %?',
    answer: 10.8, tolerance: 0.3,
    explanation: '0.6 × 14 + 0.4 × 8 × 0.75 = 8.4 + 2.4 = 10.8.',
    common_trap: 'Using pre-tax cost of debt — inflates WACC by ~80bps.',
  },
  {
    level: 3, track: 'ib_pe_vc', topic: 'Terminal value',
    question: 'FCF (terminal) $10M, g = 3%, WACC = 11%. TV ($M)?',
    answer: 128.75, tolerance: 5,
    explanation: 'TV = FCF×(1+g)/(r-g) = 10.3/0.08 ≈ 128.75.',
    common_trap: 'Forgetting (1+g) on numerator.',
  },
  {
    level: 3, track: 'ib_pe_vc', topic: 'Terminal value',
    question: 'FCF $50M, g = 2%, WACC = 10%. TV ($M)?',
    answer: 637.5, tolerance: 20,
    explanation: '50 × 1.02 / 0.08 = 51 / 0.08 = 637.5.',
    common_trap: 'Using 50/0.08 = 625 and skipping growth.',
  },
  {
    level: 3, track: 'consulting', topic: 'Price elasticity',
    question: 'Price up 10%, quantity down 15%. Elasticity?',
    answer: -1.5, tolerance: 0.1,
    explanation: 'E = %ΔQ / %ΔP = -15/10 = -1.5. Elastic (|E|>1).',
    common_trap: 'Dropping the negative sign — elasticity of demand is normally negative.',
  },
  {
    level: 3, track: 'consulting', topic: 'Price elasticity',
    question: 'Cigarette price up 20%, demand down 8%. Elasticity?',
    answer: -0.4, tolerance: 0.05,
    explanation: '-8/20 = -0.4. Inelastic (|E|<1) → raising price grows revenue.',
    common_trap: 'Calling it "elastic" because the absolute drop is large.',
  },
  {
    level: 3, track: 'consulting', topic: 'Operating leverage',
    question: 'Revenue +10%, operating profit +30%. Degree of operating leverage?',
    answer: 3, tolerance: 0.1,
    explanation: 'DOL = %Δ Op Profit / %Δ Rev = 30/10 = 3.',
    common_trap: 'Subtracting (30-10 = 20%).',
  },
  {
    level: 3, track: 'consulting', topic: 'Fixed cost absorption',
    question: 'FC ₹5Cr, units 50K. FC/unit if volumes rise 25%?',
    answer: 800, tolerance: 10,
    explanation: '50K × 1.25 = 62.5K; 5,00,00,000 / 62,500 = ₹800/unit.',
    common_trap: 'Forgetting that FC/unit *falls* as volume rises (operating leverage).',
  },
  {
    level: 3, track: 'marketing', topic: 'LTV (with churn)',
    question: 'ARPU ₹600/mo; GM 50%; monthly churn 5%. LTV (₹)?',
    answer: 6000, tolerance: 200,
    explanation: 'LTV = ARPU × GM / churn = 600 × 0.5 / 0.05 = 6,000.',
    common_trap: 'Using annual churn in a monthly ARPU formula.',
  },
  {
    level: 3, track: 'marketing', topic: 'LTV (with churn)',
    question: 'ARPU $100/mo; GM 80%; annual churn 24%. LTV ($)?',
    answer: 4000, tolerance: 200,
    explanation: 'Monthly churn ≈ 2%; LTV = 100 × 0.8 / 0.02 = 4,000. (Or 100×12×0.8/0.24.)',
    common_trap: 'Mixing monthly ARPU with annual churn rate without conversion.',
  },
  {
    level: 3, track: 'marketing', topic: 'MROI',
    question: 'Spent ₹50Lakh on a campaign; incremental gross profit ₹1.25Cr. MROI?',
    answer: 1.5, tolerance: 0.1,
    explanation: 'MROI = (Profit − Spend)/Spend = (1.25Cr − 50L) / 50L = 75L/50L = 1.5.',
    common_trap: 'Reporting gross multiple (1.25Cr/50L = 2.5) instead of net MROI.',
  },
  {
    level: 3, track: 'marketing', topic: 'CAC payback (cohort)',
    question: 'CAC ₹4,000; ARPU ₹500/mo; GM 70%. Payback (months)?',
    answer: 11.4, tolerance: 0.5,
    explanation: 'Contribution = 500 × 0.7 = 350; 4000/350 ≈ 11.4 months.',
    common_trap: 'Using ARPU directly (4000/500 = 8) and ignoring margin.',
  },
  {
    level: 3, track: 'pm', topic: 'Cohort retention',
    question: 'Cohort: 10K signups; retention 50%, 35%, 30% for M1, M2, M3. Cumulative active months in 3 mo?',
    answer: 11500, tolerance: 200,
    explanation: '10K × (0.5 + 0.35 + 0.3) = 10K × 1.15 = 11,500 active-months.',
    common_trap: 'Multiplying retention rates instead of summing for active-months.',
  },
  {
    level: 3, track: 'pm', topic: 'Statistical significance',
    question: 'A/B test: A 10% conv (n=10K), B 11% (n=10K). Z-score? (approx)',
    answer: 2.3, tolerance: 0.3,
    explanation: 'SE ≈ √(p(1−p)(2/n)) ≈ √(0.1×0.9×0.0002) ≈ 0.0042; Z = 0.01/0.0042 ≈ 2.4.',
    common_trap: 'Eyeballing 1pp lift as "obviously significant" without checking SE.',
  },
  {
    level: 3, track: 'pm', topic: 'A/B sample size',
    question: 'Detect 2pp lift on 20% baseline conversion at 80% power, α=0.05. Sample/arm? (rounded ,000)',
    answer: 6300, tolerance: 800,
    explanation: 'n ≈ 16 × p(1−p) / Δ² = 16 × 0.16 / 0.0004 = 6,400.',
    common_trap: 'Forgetting to multiply by 16 (the 80%-power, 5%-alpha rule of thumb).',
  },
  {
    level: 3, track: 'consulting', topic: 'Break-even shift',
    question: 'CM% drops from 40% to 30% on FC ₹2Cr. New breakeven revenue (₹Cr)?',
    answer: 6.67, tolerance: 0.2,
    explanation: 'BE = FC/CM = 2/0.3 ≈ 6.67Cr (was 5Cr at 40%).',
    common_trap: 'Computing breakeven units instead of revenue.',
  },
  {
    level: 3, track: 'ib_pe_vc', topic: 'Cost of equity (CAPM)',
    question: 'Rf=4%, equity premium 6%, β=1.5. Cost of equity %?',
    answer: 13, tolerance: 0.5,
    explanation: 'Ke = Rf + β × ERP = 4 + 1.5 × 6 = 13%.',
    common_trap: 'Using risk premium directly (Rf + ERP = 10%) and forgetting β.',
  },
  {
    level: 3, track: 'consulting', topic: 'Profit pool',
    question: 'Industry rev ₹5,000Cr; avg op margin 12%. Profit pool (₹Cr)?',
    answer: 600, tolerance: 10,
    explanation: '12% × 5000 = 600.',
    common_trap: 'Confusing gross margin with operating margin.',
  },
  {
    level: 3, track: 'pm', topic: 'Funnel optimization',
    question: 'Visit-pay funnel improves 1% → 1.5%. % uplift in paid users?',
    answer: 50, tolerance: 1,
    explanation: '0.5/1.0 = 50% relative uplift (not 0.5pp absolute).',
    common_trap: 'Reporting absolute (0.5pp) when the question asked for percent uplift.',
  },
  {
    level: 3, track: 'marketing', topic: 'Blended CAC',
    question: 'Paid CAC ₹2,000 (60% of users), organic CAC ₹0 (40%). Blended CAC?',
    answer: 1200, tolerance: 0,
    explanation: '0.6 × 2000 + 0.4 × 0 = 1,200.',
    common_trap: 'Averaging the two channel CACs ((2000+0)/2 = 1000) without weighting.',
  },
  {
    level: 3, track: 'consulting', topic: 'Cost curve',
    question: 'Plant cost halves with every doubling of cumulative output (50% learning curve coefficient = 2× efficient). Unit 1 = ₹100; unit 4?',
    answer: 25, tolerance: 1,
    explanation: 'Doubling 1→2→4: 100 → 50 → 25 (each doubling halves cost).',
    common_trap: 'Halving once instead of for each doubling.',
  },
  {
    level: 3, track: 'ib_pe_vc', topic: 'EV/EBITDA expansion',
    question: 'Buy EBITDA $50M at 6×; sell at 8×. EV uplift from multiple alone ($M)?',
    answer: 100, tolerance: 0,
    explanation: '50 × (8 − 6) = $100M of "multiple expansion".',
    common_trap: 'Comparing absolute EVs (300 vs 400 = $100M) — same answer here, but easy to fumble if EBITDA also grows.',
  },

  // ────────────────────────────────────────────────────────────────────
  // LEVEL 4 — expert (25 questions)
  // IRR (paper LBO), MOIC, EV bridge, accretion-dilution, tax shield,
  // real options, A/B sample size, multi-step Fermi, Bayesian update
  // ────────────────────────────────────────────────────────────────────

  {
    level: 4, track: 'ib_pe_vc', topic: 'IRR (paper)',
    question: '$300M → $1.2B in 5 yr (no cash flows). IRR %?',
    answer: 32, tolerance: 2,
    explanation: '4× in 5yr: 4^(1/5) ≈ 1.32 → IRR ≈ 32%.',
    common_trap: 'Computing simple return / years (300/5 = 60%) instead of compound.',
  },
  {
    level: 4, track: 'ib_pe_vc', topic: 'IRR (paper)',
    question: '$500M → $1.5B in 4 yr. IRR %?',
    answer: 32, tolerance: 3,
    explanation: '3× in 4yr: 3^(1/4) ≈ 1.316 → ~32%.',
    common_trap: 'Saying ~25% by anchoring on "doubles every 3 yr at 25%".',
  },
  {
    level: 4, track: 'ib_pe_vc', topic: 'MOIC',
    question: 'Entry $300M equity; exit $900M equity. MOIC?',
    answer: 3, tolerance: 0,
    explanation: '900/300 = 3×.',
    common_trap: 'Confusing with IRR (time-weighted).',
  },
  {
    level: 4, track: 'ib_pe_vc', topic: 'LBO returns',
    question: 'Entry EV $1B (60% debt); exit EV $1.5B (debt paid down to $400M). Equity MOIC?',
    answer: 2.75, tolerance: 0.2,
    explanation: 'Entry equity = 400; Exit equity = 1500-400 = 1100; 1100/400 = 2.75.',
    common_trap: 'Computing EV multiple (1.5×) instead of equity multiple.',
  },
  {
    level: 4, track: 'ib_pe_vc', topic: 'EV bridge',
    question: 'Equity $500M, debt $200M, cash $50M. EV ($M)?',
    answer: 650, tolerance: 0,
    explanation: 'EV = Equity + Debt − Cash = 500 + 200 − 50 = 650.',
    common_trap: 'Adding cash instead of subtracting it.',
  },
  {
    level: 4, track: 'ib_pe_vc', topic: 'EV bridge',
    question: 'EV $2B; debt $600M; cash $100M; minorities $50M; pension $25M. Equity value ($M)?',
    answer: 1425, tolerance: 10,
    explanation: 'Equity = EV − Debt − Minority − Pension + Cash = 2000 − 600 − 50 − 25 + 100 = 1,425.',
    common_trap: 'Forgetting minority interest / pension underfunding adjustments.',
  },
  {
    level: 4, track: 'ib_pe_vc', topic: 'Accretion-dilution',
    question: 'Acquirer EPS $4 (50M shares); target net income $30M; deal in 100% stock at $20/share. New EPS?',
    answer: 3.83, tolerance: 0.1,
    explanation: 'New shares issued: target equity / 20. If target equity ≈ $300M (10× P/E) → 15M new shares. NI: 200+30 = 230; shares 65M; EPS ≈ 3.54. Use ~$3.8 if dilutive.',
    common_trap: 'Ignoring that issuance dilutes — defaulting to (200+30)/50 = 4.6.',
  },
  {
    level: 4, track: 'ib_pe_vc', topic: 'Tax shield NPV',
    question: '$1B perpetual debt, tax rate 25%. NPV of tax shield ($M)?',
    answer: 250, tolerance: 5,
    explanation: 'Perpetual shield = D × t = 1000 × 0.25 = 250.',
    common_trap: 'Discounting interest by Kd and forgetting it cancels in perpetuity formula.',
  },
  {
    level: 4, track: 'ib_pe_vc', topic: 'Tax shield (annual)',
    question: '$500M debt at 6% interest; tax 30%. Annual tax-shield ($M)?',
    answer: 9, tolerance: 0.5,
    explanation: 'Interest = 30; shield = 30 × 30% = 9.',
    common_trap: 'Computing shield on principal directly (500 × 30% = 150).',
  },
  {
    level: 4, track: 'consulting', topic: 'Real options (heuristic)',
    question: 'Project: 30% chance of $100M payoff, 70% of $0; cost to build $20M. Expected NPV ($M)?',
    answer: 10, tolerance: 1,
    explanation: 'EV = 0.3 × 100 + 0.7 × 0 − 20 = 30 − 20 = 10.',
    common_trap: 'Forgetting the upfront cost and reporting just the expected payoff (30).',
  },
  {
    level: 4, track: 'pm', topic: 'A/B sample size',
    question: 'Detect 5% relative lift on 4% baseline conversion (Δ=0.2pp), 80% power, α=0.05. Sample/arm? (rounded thousand)',
    answer: 154000, tolerance: 30000,
    explanation: 'n ≈ 16 × p(1-p)/Δ² = 16 × 0.0384 / (0.002)² ≈ 153,600.',
    common_trap: 'Using absolute Δ of 5pp (which gives ~250 — way too small).',
  },
  {
    level: 4, track: 'consulting', topic: 'Fermi (multi-step)',
    question: 'Daily kg of bread eaten in Mumbai. Pop 20M; 60% eat bread; avg 80g/day. Tonnes/day?',
    answer: 960, tolerance: 100,
    explanation: '20M × 0.6 = 12M people × 80g = 960M g = 960 tonnes.',
    common_trap: 'Unit slips between grams / kg / tonnes (1000× errors).',
  },
  {
    level: 4, track: 'consulting', topic: 'Fermi (multi-step)',
    question: 'Annual coffee cups sold by Indian cafés. 7000 cafés × 200 cups/day × 360 days. Cups (Cr)?',
    answer: 50, tolerance: 5,
    explanation: '7000 × 200 = 14L cups/day; × 360 = 50.4Cr.',
    common_trap: 'Mixing crore and million in the final answer.',
  },
  {
    level: 4, track: 'pm', topic: 'Bayesian update',
    question: 'Prior: 1% of users are fraudsters. Detector flags fraudsters 90% of time, false-positive 5%. P(fraud | flagged)?',
    answer: 0.154, tolerance: 0.03,
    explanation: 'P = (0.01×0.9) / (0.01×0.9 + 0.99×0.05) = 0.009 / 0.0585 ≈ 0.154.',
    common_trap: 'Reporting 90% — the detector accuracy, not the posterior probability.',
  },
  {
    level: 4, track: 'pm', topic: 'Bayesian update',
    question: 'Disease prevalence 0.1%; test sens 99%, spec 95%. P(disease | positive)?',
    answer: 0.019, tolerance: 0.005,
    explanation: 'P = 0.001×0.99 / (0.001×0.99 + 0.999×0.05) ≈ 0.00099/0.0510 ≈ 1.94%.',
    common_trap: 'Trusting 99% sensitivity as the answer; base rate dominates.',
  },
  {
    level: 4, track: 'ib_pe_vc', topic: 'LBO sources & uses',
    question: 'Buy EV $500M; 5× leverage on $40M EBITDA. Equity check ($M)?',
    answer: 300, tolerance: 10,
    explanation: 'Debt = 5 × 40 = 200; Equity = EV − Debt = 500 − 200 = 300.',
    common_trap: 'Computing 5× of EV (=2,500) instead of 5× of EBITDA.',
  },
  {
    level: 4, track: 'ib_pe_vc', topic: 'IRR sensitivity',
    question: 'Hold period 5 yr; equity 3×. Approx IRR %?',
    answer: 25, tolerance: 2,
    explanation: '3^(1/5) ≈ 1.246; IRR ≈ 25%. (Useful PE rule: 3× in 5yr ≈ 25% IRR.)',
    common_trap: 'Conflating 3× MOIC with 30% IRR.',
  },
  {
    level: 4, track: 'ib_pe_vc', topic: 'Value creation bridge',
    question: 'Entry EBITDA $50M; exit $80M; multiple flat at 10×; entry net debt $300M; exit $200M. Equity uplift ($M)?',
    answer: 400, tolerance: 20,
    explanation: 'Entry equity = 500-300 = 200; Exit equity = 800-200 = 600; Δ = 400.',
    common_trap: 'Forgetting deleveraging contributes equity uplift on top of EBITDA growth.',
  },
  {
    level: 4, track: 'ib_pe_vc', topic: 'Synergy NPV',
    question: '$10M annual cost synergy in perpetuity; WACC 10%; phase-in at year 2. NPV today ($M)?',
    answer: 90, tolerance: 5,
    explanation: 'Perpetuity at year-1 view = 100; discount one year = 100/1.1 ≈ 90.9.',
    common_trap: 'Forgetting one-year delay and reporting full $100M.',
  },
  {
    level: 4, track: 'consulting', topic: 'Decision tree',
    question: 'Launch: 60% success → ₹100Cr profit; 40% fail → ₹40Cr loss. Expected value (₹Cr)?',
    answer: 44, tolerance: 1,
    explanation: '0.6 × 100 + 0.4 × (−40) = 60 − 16 = 44.',
    common_trap: 'Treating "loss" as a positive number in EV math.',
  },
  {
    level: 4, track: 'marketing', topic: 'Attribution',
    question: 'Last-click shows 60% paid, 40% organic. With 3-touch even attribution, paid touches in 2 of 3 typical journeys. Adjusted paid share?',
    answer: 67, tolerance: 5,
    explanation: 'Even-credit: 2/3 of paid touches = ~67% paid share.',
    common_trap: 'Sticking with last-click 60% — not realising attribution model rebalances credit.',
  },
  {
    level: 4, track: 'marketing', topic: 'Incrementality',
    question: 'Holdout test: control group 5% conversion, treatment 7%. Incremental conversions per 1,000 ad-exposed users?',
    answer: 20, tolerance: 2,
    explanation: 'Lift = 2pp; × 1000 = 20 incremental conversions.',
    common_trap: 'Using treatment rate alone (70 conversions) and ignoring counterfactual.',
  },
  {
    level: 4, track: 'pm', topic: 'Network effects (sizing)',
    question: 'Marketplace: 10K sellers + 100K buyers; value scales as buyers × sellers. % uplift if buyers double?',
    answer: 100, tolerance: 0,
    explanation: 'V ∝ B × S; doubling B with S flat → 2× → 100% uplift.',
    common_trap: 'Citing Metcalfe (n²) and reporting 4× — only true if both sides grow.',
  },
  {
    level: 4, track: 'consulting', topic: 'Multi-step margin',
    question: 'Brand: ₹100 MRP → 15% retailer margin → 10% distributor margin → 8% GST on net. Net realisation to brand (₹)?',
    answer: 70.83, tolerance: 2,
    explanation: 'Strip retailer: 100/1.15 ≈ 86.96; strip distributor: /1.10 ≈ 79.05; strip GST: /1.08 ≈ 73.2. Approx ~70-73.',
    common_trap: 'Subtracting margins additively (15+10+8 = 33% off → ₹67) instead of compounding.',
  },
  {
    level: 4, track: 'ib_pe_vc', topic: 'Accretion-dilution (quick)',
    question: 'Acquirer P/E 20×; target P/E 12×. All-stock deal. Accretive or dilutive?',
    answer: 1, tolerance: 0,
    explanation: 'Buying lower P/E with higher P/E stock is accretive. Code 1 = accretive, 0 = dilutive.',
    common_trap: 'Reversing the rule — high P/E acquirer + low P/E target *is* accretive (ignoring synergies/premium).',
  },
];
