// Product Management deep content

import type { FrameworkDeep, MathDrill, IndustryPrimer } from './tracks-deep';

export const PM_FRAMEWORKS: FrameworkDeep[] = [
  { name: 'CIRCLES', when_to_use: 'Product design questions ("design X for Y")', when_NOT_to_use: 'Estimation / metrics-driven Qs', structure: ['Comprehend the situation', 'Identify the customer', 'Report customer needs', 'Cut by priority', 'List solutions', 'Evaluate trade-offs', 'Summarize recommendation'], example: 'Design product for visually impaired commuters → C: peak-hour navigation, I: 28M legally blind in India, R: real-time obstacle alerts, etc.' },
  { name: 'AARRR (Pirate Metrics)', when_to_use: 'Growth funnel, retention diagnosis', when_NOT_to_use: 'Strategy / positioning Qs', structure: ['Acquisition (channel, CAC)', 'Activation (first AHA moment)', 'Retention (D1/D7/D30 curves)', 'Referral (viral coefficient)', 'Revenue (LTV, ARPU)'], example: 'Notion: A=SEO + word-of-mouth, Activation=create first page, R=workspace stickiness, Referral=team invites, Rev=team plan upgrade.' },
  { name: 'GAME', when_to_use: 'Product strategy Qs', when_NOT_to_use: 'Tactical metric Qs', structure: ['Goals (north star, KPIs)', 'Acts (initiatives to achieve)', 'Metrics (success measure per Act)', 'Evaluate (criteria + trade-offs)'], example: 'YouTube Shorts: Goals=engagement min, Acts=creator monetization + ranking algo, Metrics=time spent, Evaluate=cannibalization risk.' },
  { name: 'JTBD (Jobs-to-be-Done)', when_to_use: 'Reframe what a customer is trying to achieve', when_NOT_to_use: 'When demographic targeting is sufficient', structure: ['Functional job (the task)', 'Emotional job (how they want to feel)', 'Social job (how they want to be perceived)', 'Pain points blocking the job'], example: 'Milkshake JTBD on commute: function=fill stomach, emotional=morning ritual, social=affordable indulgence.' },
  { name: 'Kano Model', when_to_use: 'Feature prioritization', when_NOT_to_use: 'Single-feature design', structure: ['Must-haves (table-stakes — absence kills)', 'Performance (more is better, scales linearly)', 'Delighters (unexpected — drive love)', 'Indifferent (drop)', 'Reverse (negative — drop)'], example: 'Dropbox: must=storage works, performance=speed, delighter=auto-photo backup.' },
  { name: 'RICE Prioritization', when_to_use: 'Roadmap prioritization', when_NOT_to_use: 'Strategic / vision Qs', structure: ['Reach (users affected per quarter)', 'Impact (per-user, 0.25 to 3)', 'Confidence (% based on evidence)', 'Effort (person-months)', 'Score = R×I×C / E'], example: 'Feature A: 10K reach × 1.0 impact × 80% confidence / 2 months = 4000 score.' },
  { name: 'North Star Framework', when_to_use: 'Picking THE success metric', when_NOT_to_use: 'Day-to-day execution', structure: ['Long-term value indicator (lagging)', 'Counter-metric for quality', 'Leading indicators upstream', 'Inputs the team controls'], example: 'Airbnb: Nights booked (NSM), guest satisfaction (counter), search-to-book conv (leading), supply growth (input).' },
  { name: 'Root Cause / 5 Whys', when_to_use: 'Metric dropped, find why', when_NOT_to_use: 'Strategy questions', structure: ['Segment by user / time / geography / device', 'Ask "why" 5 times', 'Distinguish external vs internal causes', 'Hypothesize → test with data'], example: 'DAU dropped 8%. Why? Android only. Why? Last release. Why? Crash bug. Why? Untested OS version. Root cause: QA gap.' },
  { name: 'A/B Test Design', when_to_use: 'Validate a change', when_NOT_to_use: 'Brand-new bets without baseline', structure: ['Hypothesis (specific, measurable)', 'Primary metric + counter-metric', 'Sample size (effect size, power)', 'Duration (cover weekly cycle)', 'Decision criteria + ramp plan'], example: 'New checkout: H = +5% conv. Primary = checkout conv, counter = AOV. n=100K, 14d, ship if p<0.05 and counter unmoved.' },
  { name: 'Funnel Analysis', when_to_use: 'Conversion drop diagnosis', when_NOT_to_use: 'Strategy / positioning', structure: ['Define funnel stages clearly', 'Compute conversion at each step', 'Identify biggest drop-off', 'Hypothesize cause', 'Run experiment'], example: 'Signup funnel: 100 land → 70 click signup → 50 enter email → 30 verify → 20 complete. Verify-step conv 60% is the leak.' },
  { name: 'Cohort Analysis', when_to_use: 'Retention / LTV diagnostic', when_NOT_to_use: 'Single-event metrics', structure: ['Group users by signup month/feature', 'Track retention curve per cohort', 'Compare cohorts to spot improvements/decay', 'Identify cohort with best behavior + replicate'], example: 'Cohort post-onboarding redesign retains 40% at D30 vs 25% before. Roll out broadly.' },
  { name: 'PMF Survey (Sean Ellis)', when_to_use: 'Validate product-market fit', when_NOT_to_use: 'Mature product optimization', structure: ['Ask: "How would you feel if you could no longer use the product?"', 'Threshold: 40% answer "very disappointed" = PMF', 'Segment by user type to find core users', 'Double down on core'], example: 'Superhuman: 22% → asked very-disappointed users why → built engine to convert 22% into more.' },
  { name: 'Decision Tree (PM)', when_to_use: 'Branching feature decision', when_NOT_to_use: 'Linear / single-path Qs', structure: ['Root: should we build X?', 'Branches: success criteria, failure modes', 'Sub-branches: dependencies, costs', 'Decide path with highest expected value'], example: 'Build voice feature? → if user research positive → if eng feasible → if revenue >$5M EV → build. Else → Wizard of Oz first.' },
  { name: 'OKR Framework', when_to_use: 'Setting team goals', when_NOT_to_use: 'Individual performance management', structure: ['Objective (qualitative, ambitious)', 'Key Results (3-5, measurable, aspirational)', 'Owner per KR', 'Quarterly review'], example: 'Obj: best mobile reading experience. KR1: time-in-app +30%, KR2: NPS 50, KR3: D7 retention 60%.' },
  { name: 'Pirate Funnel + Forecast', when_to_use: 'Growth modeling for new launch', when_NOT_to_use: 'Mature product optimization', structure: ['Acquisition forecast (channels, CAC trend)', 'Activation rate', 'Retention curve assumed', 'Compute MAU + revenue trajectory'], example: 'New SaaS: 1K signups/mo × 30% activate × 60% D30 retain → 180 MAU added/mo, $50K ARR by Q3.' },
  { name: 'Product Strategy 6-pack', when_to_use: 'Comprehensive strategy answer', when_NOT_to_use: 'Tactical Qs', structure: ['Why (mission)', 'Who (target user)', 'What (product offering)', 'How (differentiation)', 'When (timing)', 'Win condition (success metric)'], example: 'Notion strategy: why=knowledge work, who=teams, what=block editor, how=infinite flexibility, when=Slack era, win=team plan ARR.' },
];

export const PM_MATH: MathDrill[] = [
  { level: 1, name: 'Funnel conversion', formula: 'Step N / Step N-1', shortcut: 'Multiply step ratios for full-funnel conversion', example: '70% × 50% × 60% = 21% end-to-end', threshold_to_advance: 'Identify biggest drop' },
  { level: 1, name: 'WAU / MAU ratio (stickiness)', formula: 'WAU / MAU', shortcut: '>50% = high engagement, daily-use', example: 'WAU 5M / MAU 8M = 62%', threshold_to_advance: 'Connect to retention' },
  { level: 1, name: 'DAU / MAU', formula: 'DAU / MAU', shortcut: '>20% = strong daily product', example: 'DAU 1M / MAU 4M = 25%', threshold_to_advance: 'Compare across product types' },
  { level: 2, name: 'Retention curve', formula: 'Day-N active / Day-0 active', shortcut: 'D1>50%, D7>30%, D30>20% = strong product', example: 'Cohort: 100 → D1 70 → D7 40 → D30 25', threshold_to_advance: 'Detect cohort improvements' },
  { level: 2, name: 'Churn rate', formula: 'Lost users / total users in period', shortcut: 'Monthly: <5% B2B SaaS, <10% B2C consumer', example: '500 churned / 10K = 5%', threshold_to_advance: 'Distinguish revenue vs logo churn' },
  { level: 2, name: 'LTV (simple)', formula: 'ARPU × gross margin × (1 / churn rate)', shortcut: 'ARPU × GM / monthly churn × 12 for years', example: 'ARPU $50, GM 70%, churn 3%/mo → LTV $1167', threshold_to_advance: 'Adjust for retention curve' },
  { level: 2, name: 'CAC', formula: 'Marketing spend / new customers', shortcut: 'By channel, by cohort', example: '$1M spend / 5K acquired = $200', threshold_to_advance: 'Blended vs paid CAC' },
  { level: 2, name: 'LTV / CAC', formula: 'LTV / CAC', shortcut: '>3x healthy, <1x burning', example: 'LTV $900 / CAC $300 = 3x', threshold_to_advance: 'Connect to payback period' },
  { level: 2, name: 'CAC payback', formula: 'CAC / monthly contribution margin', shortcut: '<12mo for B2C, <24mo for B2B', example: 'CAC $200 / $20/mo CM = 10mo', threshold_to_advance: 'Connect to growth rate' },
  { level: 2, name: 'Engagement rate', formula: '(Likes + Comments + Shares) / Views', shortcut: '<1% poor, 1-3% good, >5% great', example: '50K engagements / 2M views = 2.5%', threshold_to_advance: 'Vary by platform' },
  { level: 3, name: 'Fermi estimation', formula: 'Population × % users × frequency × duration × revenue', shortcut: 'Decompose then estimate each multiplier', example: 'Coffee in Mumbai: 20M × 30% × 1.5/day × ₹150 = ₹1.35B/day', threshold_to_advance: 'Sanity-check against known total' },
  { level: 3, name: 'North Star Math', formula: 'NSM = (active users) × (frequency) × (value)', shortcut: 'Decompose to find leverage point', example: 'Airbnb nights = (guests × trips × nights/trip)', threshold_to_advance: 'Pick the right NSM' },
  { level: 3, name: 'Power user concentration', formula: '% of value from top 10/20% users', shortcut: 'Pareto: typically 80/20 or worse', example: 'Reddit: 1% of users create 50% of content', threshold_to_advance: 'Find counter-Pareto' },
  { level: 3, name: 'Viral coefficient (k-factor)', formula: 'Invites sent × invite-acceptance rate', shortcut: 'k>1 = viral growth, k<1 = decay', example: 'Each user invites 10, 15% accept → k=1.5', threshold_to_advance: 'Time to double users' },
  { level: 4, name: 'Statistical significance (A/B)', formula: 'p-value < 0.05, sample size sufficient', shortcut: 'Need ~16 / (effect size)² × variance', example: '5% effect: ~10K per arm typical for 80% power', threshold_to_advance: 'Distinguish effect size from p-value' },
  { level: 4, name: 'Bayesian update', formula: 'Posterior ∝ Prior × Likelihood', shortcut: 'Update belief after data', example: 'Prior 30% feature works → data shows lift → posterior 70%', threshold_to_advance: 'Apply to roadmap decisions' },
];

// App-specific KPI cheat sheet
export const PM_APP_KPIS: { app: string; sector: string; key_metrics: string[]; north_star: string; counter: string }[] = [
  { app: 'Instagram', sector: 'social', key_metrics: ['DAU', 'time spent', 'stories views', 'reels views', 'post engagement rate'], north_star: 'Time spent', counter: 'Negative content reports' },
  { app: 'Spotify', sector: 'music', key_metrics: ['MAU', 'songs/session', 'D90 retention', 'Premium %', 'discovery → save rate'], north_star: 'Time-listened', counter: 'Skip rate' },
  { app: 'Uber', sector: 'mobility', key_metrics: ['rides/month', 'driver liquidity', 'wait time', 'cancellation rate', 'GMV'], north_star: 'Rides per quarter', counter: 'Cancellation rate' },
  { app: 'Netflix', sector: 'streaming', key_metrics: ['MAU', 'hours/user/week', 'completion rate', 'churn', 'ARPU'], north_star: 'Hours streamed', counter: '30-day churn' },
  { app: 'Airbnb', sector: 'travel', key_metrics: ['nights booked', 'host listings', 'search → book conv', 'guest NPS', 'repeat rate'], north_star: 'Nights booked', counter: 'Cancellation rate' },
  { app: 'Slack', sector: 'work', key_metrics: ['team daily-actives', 'messages/user/day', 'integration count', 'team retention'], north_star: 'Messages per team', counter: 'Notification opt-outs' },
  { app: 'Notion', sector: 'productivity', key_metrics: ['pages created', 'team members', 'NRR', 'D7 retention', 'integrations enabled'], north_star: 'Active blocks/team/week', counter: 'Page deletions' },
  { app: 'TikTok', sector: 'social', key_metrics: ['watch time', 'completion rate', 'creator → viewer ratio', 'shares', 'follow conv'], north_star: 'Time spent', counter: 'Misinformation reports' },
  { app: 'LinkedIn', sector: 'professional', key_metrics: ['MAU', 'posts/user', 'connection acceptance', 'job applies', 'premium conv'], north_star: 'Sessions per professional', counter: 'Spam reports' },
  { app: 'YouTube', sector: 'video', key_metrics: ['watch time', 'completion %', 'creator earnings', 'subscriber growth'], north_star: 'Hours watched', counter: 'Demonetization complaints' },
];

export const PM_INDUSTRY_PRIMERS: IndustryPrimer[] = [
  { sector: 'Social media', typical_margin_range: 'EBITDA 30-45%', cycle_or_kpi: 'DAU/MAU, time spent, ad ARPU, content velocity', cost_drivers: ['Infra (CDN)', 'Content moderation', 'R&D'], revenue_drivers: ['Ad impressions × CPM', 'Time spent', 'Targeting precision'], recent_disruption: 'GenAI generated content, regulatory pressure on minors, TikTok everywhere', diagnostic_q_for_interviewer: 'Time-spent trend + content moderation cost?' },
  { sector: 'SaaS (B2B)', typical_margin_range: 'GM 70-85%, EBITDA 20-35% mature', cycle_or_kpi: 'ARR, NRR, gross retention, CAC payback, magic number', cost_drivers: ['R&D', 'S&M', 'Hosting'], revenue_drivers: ['New ARR', 'Expansion (NRR>110%)', 'Churn'], recent_disruption: 'GenAI commoditizing some categories, vertical AI agents', diagnostic_q_for_interviewer: 'Net retention by customer cohort?' },
  { sector: 'Marketplace / 2-sided', typical_margin_range: 'Take rate 5-25%, EBITDA varies', cycle_or_kpi: 'GMV, take rate, supply density, liquidity', cost_drivers: ['Subsidies', 'Marketing', 'Trust & safety', 'Payments'], revenue_drivers: ['GMV growth', 'Take rate', 'Adjacent services'], recent_disruption: 'Disintermediation (DTC), platform regulation, AI-driven matching', diagnostic_q_for_interviewer: 'Liquidity by geo/category?' },
  { sector: 'Streaming / OTT', typical_margin_range: 'EBITDA 10-25% mature', cycle_or_kpi: 'Subs, churn, hours/sub, content cost / hour', cost_drivers: ['Content (50%+)', 'Infra/CDN', 'Marketing'], revenue_drivers: ['Subs growth', 'ARPU', 'Ad tier'], recent_disruption: 'Password-sharing crackdown, ad-tiers, FAST channels', diagnostic_q_for_interviewer: 'Content ROI by genre?' },
  { sector: 'Fintech / payments', typical_margin_range: 'Take 0.5-2.5%, scale-driven', cycle_or_kpi: 'TPV, take rate, monetization per user, fraud rate', cost_drivers: ['Interchange / network fees', 'Fraud losses', 'Compliance'], revenue_drivers: ['TPV growth', 'Take rate', 'Cross-sell (lending, insurance)'], recent_disruption: 'Real-time payments (UPI/Pix), embedded finance, stablecoins', diagnostic_q_for_interviewer: 'Take rate compression vs cross-sell offset?' },
  { sector: 'Edtech', typical_margin_range: 'GM 50-70%, EBITDA −10 to 10% (often loss)', cycle_or_kpi: 'Enrolled students, completion rate, NPS, CAC', cost_drivers: ['CAC (very high)', 'Content/teachers', 'Tech'], revenue_drivers: ['Enrollments', 'Course price', 'Renewal'], recent_disruption: 'GenAI tutors, micro-credentials, free content abundance', diagnostic_q_for_interviewer: 'Completion rate + LTV/CAC by channel?' },
];
