// Deep content layer for each track — extends the slim tracks.ts with the
// full spec content (20+ frameworks per track, 30+ math drills sequenced,
// 12 industry primers, 30 behavioral Qs with STAR scaffolds, etc.).
// Imported by /cheatsheet and /api routes.

import type { Track } from './tracks';

export interface FrameworkDeep {
  name: string;
  when_to_use: string;
  when_NOT_to_use: string;
  structure: string[];
  example: string;
}

export interface MathDrill {
  level: 1 | 2 | 3 | 4; // 1 = beginner, 4 = expert
  name: string;
  formula: string;
  shortcut: string;
  example: string;
  threshold_to_advance: string;
}

export interface IndustryPrimer {
  sector: string;
  typical_margin_range: string;
  cycle_or_kpi: string;
  cost_drivers: string[];
  revenue_drivers: string[];
  recent_disruption: string;
  diagnostic_q_for_interviewer: string;
}

export interface BehavioralQ {
  prompt: string;
  dimension: 'connection' | 'drive' | 'leadership' | 'growth' | 'judgment' | 'curiosity' | 'resilience';
  star_scaffold: string;
  spike_move: string;
  common_mistake: string;
}

// CONSULTING — full content
export const CONSULTING_FRAMEWORKS: FrameworkDeep[] = [
  { name: 'Profitability Tree', when_to_use: 'Profit dropped, margin compression, cost-out / revenue-up case', when_NOT_to_use: 'Pure market entry / sizing — use 3C or sizing instead', structure: ['Profit = Revenue − Cost', 'Revenue = Price × Volume', 'Volume = (existing customers × frequency × per-unit) + (new customers × ...)', 'Cost = Fixed + Variable', 'Variable = COGS + SG&A + distribution', 'Identify which sub-driver moved'], example: 'Steel co profit dropped 30% — segment by volume vs price; volume is flat, price is down 25% due to substitute (carbon fiber). Driver = price.' },
  { name: 'Market Entry', when_to_use: 'Should client enter new market / geography / product', when_NOT_to_use: 'Profitability cases — entry is a strategic question', structure: ['Market attractiveness (size, growth, profitability, fragmentation)', 'Client fit (capabilities, capital, brand, channels)', 'Entry mode (greenfield, acquisition, JV, license)', 'Risks (regulatory, competitive response, execution)'], example: 'Cement major into India — market 380MT/yr growing 8%, fragmented (top-5 = 50%), client has tech advantage but no distribution. Recommend acquisition.' },
  { name: 'M&A', when_to_use: 'Acquisition, divestiture, JV decision', when_NOT_to_use: 'Internal organic growth — use growth strategy', structure: ['Strategic fit (revenue / cost synergies, capability gap closure)', 'Financial fit (NPV, accretive, payback)', 'Cultural fit (org compatibility)', 'Integration risk (timeline, retention, regulatory)'], example: 'Pharma A acquires biotech B for pipeline — synergy in R&D, but B\'s scientists likely to leave. Suggest acqui-hire structure.' },
  { name: 'Pricing', when_to_use: 'New product price, price change, price discrimination', when_NOT_to_use: 'Cost-out — pricing solves revenue not cost', structure: ['Cost-based (cost + margin) — floor', 'Competitor-based (vs alternatives) — ceiling', 'Value-based (willingness to pay × % capture) — true price', 'Elasticity (volume response to price change)'], example: 'New drug for rare disease — value-based: lifetime cost saved $200K, capture 30% = $60K/yr.' },
  { name: 'Operations / Process', when_to_use: 'Capacity, throughput, lean, cost reduction in operations', when_NOT_to_use: 'Strategic positioning cases', structure: ['Process map step-by-step', 'Identify bottleneck (theory of constraints)', 'Utilization (% of capacity used)', 'Quality / defect rate', 'Variability (cycle time SD)'], example: 'Hospital ER throughput — bottleneck is doctor consult (15min/patient). Adding nurses doesn\'t help; adding doctors or triage does.' },
  { name: 'Market Sizing', when_to_use: 'Estimate market size, addressable units, demand', when_NOT_to_use: 'Strategy questions — sizing alone isn\'t a recommendation', structure: ['Top-down: population × % adopters × frequency × price', 'Bottom-up: outlets × throughput × price', 'Sanity-check both vs published #'], example: 'Coffee in Mumbai — 20M people × 30% drink coffee × 1.5 cups/day × ₹150 = ₹1100Cr/yr.' },
  { name: '3C', when_to_use: 'Strategy / market entry overview', when_NOT_to_use: 'Tactical cases — too high-level', structure: ['Customer (segments, needs, behavior, willingness to pay)', 'Company (capabilities, brand, costs, channels)', 'Competition (market share, positioning, response moves)'], example: 'Beverage co launching premium tea — customer = young urban; company has cold-chain; competition = Lipton dominates mass.' },
  { name: '4P / Marketing Mix', when_to_use: 'GTM, brand, positioning, campaign', when_NOT_to_use: 'Cost cases — 4P is revenue-side', structure: ['Product (features, quality, brand, packaging)', 'Price (level, discount, payment terms)', 'Place (channels, geography, retail vs DTC)', 'Promotion (advertising, PR, sales force)'], example: 'New EV scooter — premium product, price 30% above ICE, place = experience centers in metros, promotion = lifestyle influencers.' },
  { name: 'Porter 5 Forces', when_to_use: 'Industry attractiveness, structural analysis', when_NOT_to_use: 'Specific company / case-level decisions', structure: ['Buyer power (concentration, switching cost)', 'Supplier power (concentration, substitutes)', 'New entrants (barriers — capital, regulation, brand)', 'Substitutes (X-industry alternatives)', 'Rivalry (concentration, growth, exit barriers)'], example: 'Airline industry — high rivalry, low buyer power per ticket but high via aggregators, low entrant barriers (LCC), substitute = video calls / rail.' },
  { name: 'BCG Growth-Share', when_to_use: 'Portfolio decisions, capital allocation', when_NOT_to_use: 'Single-business cases', structure: ['Stars (high share, high growth) — invest', 'Cash cows (high share, low growth) — milk', 'Question marks (low share, high growth) — selective bet', 'Dogs (low share, low growth) — divest'], example: 'Conglomerate with 4 businesses — paint = cow (50% share, 5% growth), EV = ?, FMCG = star, telecom = dog.' },
  { name: 'Issue Tree', when_to_use: 'Generic root cause / structuring', when_NOT_to_use: 'When a domain framework fits better', structure: ['Top question', 'MECE branches (max 3-4)', 'Sub-branches', 'Hypothesis at each leaf'], example: 'Why is the magazine declining? — Internal (content, price, distribution) / External (reader habits, competition) / Ad market (CPM, partners).' },
  { name: 'Driver Tree', when_to_use: 'Diagnose KPI movement', when_NOT_to_use: 'Strategic positioning', structure: ['Top metric', 'Mathematical decomposition (× and +)', 'Each leaf is a measurable lever', 'Quantify movement of each'], example: 'CAC up 40% — = (marketing spend / new customers). Spend +20%, customers −15% (= conversion ↓ × traffic ↑).' },
  { name: 'Hypothesis-Driven', when_to_use: 'Time-pressed cases / late-stage interviews', when_NOT_to_use: 'When hypothesis would feel premature', structure: ['State hypothesis upfront ("I think X because Y")', 'Identify key data needed to test', 'Gather → confirm or pivot', 'Synthesize bottom-line first'], example: '"My hypothesis is the price drop, not volume — let me confirm with the price/volume split."' },
  { name: 'Value Chain', when_to_use: 'Cost analysis across operations', when_NOT_to_use: 'Pure revenue / market questions', structure: ['Inbound logistics', 'Operations', 'Outbound logistics', 'Marketing & sales', 'Service', 'Plus support: HR, tech, infra, procurement'], example: 'Auto OEM cost-out — biggest leverage in operations (60%) and inbound (25%); back office is <5%.' },
  { name: 'PESTEL', when_to_use: 'Macro-environmental scan, regulatory case', when_NOT_to_use: 'Tactical questions — PESTEL is too broad', structure: ['Political', 'Economic', 'Social', 'Technological', 'Environmental', 'Legal'], example: 'EV adoption in India — Political (subsidy ↑), Economic (price gap closing), Social (urban awareness ↑), Tech (battery $/kWh ↓), Env (pollution mandates), Legal (FAME II).' },
  { name: 'McKinsey 7S', when_to_use: 'Org-design / change-management cases', when_NOT_to_use: 'Strategy / market cases', structure: ['Strategy', 'Structure', 'Systems', 'Shared values', 'Style', 'Staff', 'Skills'], example: 'Post-merger integration — strategy aligned but systems & staff misaligned; structure forced before culture.' },
  { name: 'STP (Marketing)', when_to_use: 'Targeting / positioning step before 4P', when_NOT_to_use: 'Standalone, always pair with 4P', structure: ['Segment (demographic, behavioral, needs)', 'Target (which segment to win)', 'Position (point of difference, frame of reference)'], example: 'Hippo baked snack — segment = health-conscious urban youth, target = 18-25 SEC-A, position = "tasty without the guilt".' },
  { name: 'SWOT', when_to_use: 'Quick situational diagnosis', when_NOT_to_use: 'When a structured tree would be deeper', structure: ['Strengths (internal +)', 'Weaknesses (internal −)', 'Opportunities (external +)', 'Threats (external −)'], example: 'Hippo SWOT — S: Parle distribution; W: brand health vs Lays; O: clean-label trend; T: regional D2C brands.' },
  { name: 'Ansoff Matrix', when_to_use: 'Growth strategy decision', when_NOT_to_use: 'Cost / operational cases', structure: ['Market penetration (existing × existing)', 'Product development (new × existing market)', 'Market development (existing product × new market)', 'Diversification (new × new) — riskiest'], example: 'IT services co — penetration plateaued, dev new GenAI offerings, expand to LATAM, avoid diversification into hardware.' },
  { name: 'Customer Decision Journey', when_to_use: 'Funnel / conversion cases, brand awareness', when_NOT_to_use: 'Cost / operational', structure: ['Awareness', 'Consideration', 'Evaluation', 'Purchase', 'Post-purchase / loyalty'], example: 'EV scooter — high awareness, low consideration (range anxiety), drop-off at evaluation (test ride access). Fix = experience centers.' },
  { name: 'Real Options', when_to_use: 'Sequential investment, R&D, staged decisions', when_NOT_to_use: 'Standard NPV cases', structure: ['Identify staged decisions', 'Value option to delay / expand / abandon', 'Sensitivity to volatility'], example: 'Phase 1 trial — option to continue if positive, abandon if not. Worth more than NPV-only because uncertainty is high.' },
];

export const CONSULTING_MATH: MathDrill[] = [
  { level: 1, name: 'Percentage', formula: 'part / whole × 100', shortcut: '10% then ×n: 12% of 350 = 35 + 7 = 42', example: '12% of 350 = 42', threshold_to_advance: 'Solve 5 in <10s each' },
  { level: 1, name: 'Growth rate', formula: '(new − old) / old', shortcut: 'Δ over base; subtract 1 from ratios', example: '120 → 144 = 20% growth', threshold_to_advance: '5 correct in 30s' },
  { level: 1, name: 'Multiplication shortcut', formula: 'Round + adjust', shortcut: '47 × 38 ≈ 50 × 40 = 2000, then −150 (3×50) −80 (2×40) = ~1786', example: '47 × 38 ≈ 1786', threshold_to_advance: '3 correct in <15s' },
  { level: 1, name: 'Division', formula: 'a / b', shortcut: 'Multiply both by 10s to integerize; estimate by closest known', example: '4500 / 35 ≈ 4500/35 ≈ 128 (35×130=4550)', threshold_to_advance: '3 correct in <20s' },
  { level: 2, name: 'CAGR', formula: '(end / start)^(1/n) − 1', shortcut: 'Rule of 72: years to double = 72 / rate%', example: 'Doubles in 9 years → ~8% CAGR', threshold_to_advance: 'Estimate within ±1pp' },
  { level: 2, name: 'Breakeven units', formula: 'Fixed / (Price − VC)', shortcut: 'Fixed / Contribution per unit', example: 'FC=1M, P=100, VC=60 → 25K units', threshold_to_advance: '3 correct in <30s' },
  { level: 2, name: 'Contribution margin %', formula: '(P − VC) / P', shortcut: '1 − (VC/P)', example: 'P=100, VC=60 → 40%', threshold_to_advance: '5 correct quickly' },
  { level: 2, name: 'Payback period', formula: 'Investment / Annual cash flow', shortcut: 'Years to recover initial', example: '$10M / $2M/yr = 5yr', threshold_to_advance: 'Solve with mixed-sign flows' },
  { level: 2, name: 'Market sizing top-down', formula: 'Pop × adoption × usage × price', shortcut: 'Decompose population by income / age / urbanity', example: 'India coffee = 1.4B × 8% × 100 cups/yr × ₹100 = ₹1.1L Cr', threshold_to_advance: 'Sanity check vs known total' },
  { level: 2, name: 'Market sizing bottom-up', formula: 'Outlets × throughput × price', shortcut: 'Use known retail / store density numbers', example: '50K cafes × 200 cups/day × ₹150 × 365 ≈ ₹55K Cr', threshold_to_advance: 'Cross-check vs top-down' },
  { level: 3, name: 'NPV (5-year)', formula: 'Σ CF_t / (1+r)^t − Investment', shortcut: 'For r=10%: ~3.8x of avg CF over 5 years', example: '$2M/yr for 5yr at 10% = ~$7.6M PV', threshold_to_advance: 'Estimate ±5%' },
  { level: 3, name: 'WACC', formula: '(E/V × Re) + (D/V × Rd × (1−T))', shortcut: 'Weighted average; debt is cheaper after tax', example: '60% equity at 12% + 40% debt at 6%(1−0.3) = 7.2 + 1.68 = 8.9%', threshold_to_advance: 'Solve with given inputs' },
  { level: 3, name: 'Terminal value (Gordon)', formula: 'FCF × (1+g) / (WACC − g)', shortcut: '~10× FCF if g=3%, WACC=12%', example: 'FCF=10, g=3%, WACC=11% → 10×1.03/0.08 = 128.75', threshold_to_advance: 'Sensitivity to g' },
  { level: 3, name: 'Price elasticity', formula: '%ΔQ / %ΔP', shortcut: 'Negative for normal goods; |E|>1 = elastic', example: 'Price up 10%, qty down 15% → E = −1.5 (elastic)', threshold_to_advance: 'Predict revenue impact' },
  { level: 3, name: 'Operating leverage', formula: '%ΔEBIT / %ΔSales', shortcut: 'High fixed cost = high leverage', example: 'Sales +10% → EBIT +30% means leverage = 3', threshold_to_advance: 'Identify high-OL businesses' },
  { level: 4, name: 'Paper LBO', formula: 'Entry: EBITDA × multiple − debt; Exit: Yr5 EBITDA × exit multiple', shortcut: 'Target IRR 20-25%, MOIC 2-3x', example: '$100M EBITDA × 8 − $500M debt = $300M equity. Yr5: $150M × 9 = $1350M EV − $200M debt = $1150M equity. MOIC ~3.8x, IRR ~30%', threshold_to_advance: 'Compute in 5 min' },
  { level: 4, name: 'IRR (paper)', formula: '(Exit / Entry)^(1/n) − 1', shortcut: '2x in 5yr ≈ 15% IRR; 3x ≈ 25%', example: '$300M → $1B in 5yr → 27% IRR', threshold_to_advance: 'Match published deal IRRs' },
  { level: 4, name: 'EV bridge', formula: 'EV = Equity + Debt − Cash', shortcut: 'EV = what an acquirer pays in full', example: 'Equity $500M, debt $200M, cash $50M → EV $650M', threshold_to_advance: 'Move between EV and Equity' },
];

export const CONSULTING_INDUSTRY_PRIMERS: IndustryPrimer[] = [
  { sector: 'FMCG (food, personal care, household)', typical_margin_range: 'GM 40-50%, EBITDA 15-25%', cycle_or_kpi: 'Volume growth (vs price), penetration, repeat rate, distribution width', cost_drivers: ['Raw materials (commodity-linked)', 'A&P spend (10-15% of sales)', 'Distribution / trade margins (10-20%)'], revenue_drivers: ['Distribution width (# outlets)', 'Penetration', 'Per-capita consumption', 'Premiumization (mix)'], recent_disruption: 'D2C brands eating share in personal care, urban metros; quick-commerce changing distribution', diagnostic_q_for_interviewer: 'Is the volume issue driven by penetration or premiumization mix?' },
  { sector: 'Retail / e-commerce', typical_margin_range: 'GM 25-40% (depending on private label %), EBITDA 5-10%', cycle_or_kpi: 'GMV, AOV, repeat purchase, inventory turns, contribution margin', cost_drivers: ['COGS', 'Logistics & fulfillment', 'Marketing CAC', 'Returns & write-offs'], revenue_drivers: ['Customer count', 'Order frequency', 'AOV', 'Take rate (for marketplace)'], recent_disruption: 'Quick-commerce (10-min delivery), live-commerce, AI-powered search', diagnostic_q_for_interviewer: 'Is retention dropping by cohort or just acquisition slowing?' },
  { sector: 'Banking / financial services', typical_margin_range: 'NIM 2.5-4%, ROE 12-18%', cycle_or_kpi: 'NIM, cost-to-income, NPA, deposit growth, fee income mix', cost_drivers: ['Cost of funds', 'Operating expenses (branches, tech)', 'Provisioning / credit cost'], revenue_drivers: ['Loan book growth', 'NIM', 'Fee income', 'Cross-sell'], recent_disruption: 'Neobanks (fee compression), UPI (zero-MDR), embedded finance, GenAI for underwriting', diagnostic_q_for_interviewer: 'Is the margin compression from rate competition or asset quality?' },
  { sector: 'Healthcare / hospitals', typical_margin_range: 'EBITDA 18-25%, clinic-level margins higher', cycle_or_kpi: 'ARPOB, ALOS, occupancy %, payor mix, doctor productivity', cost_drivers: ['Doctor salaries', 'Pharmacy / consumables', 'Capex on equipment', 'Real estate'], revenue_drivers: ['Bed days', 'Procedure mix (cardiac > general)', 'Payor mix', 'Insurance penetration'], recent_disruption: 'Day-care surgery centers, telemedicine, AI diagnostics', diagnostic_q_for_interviewer: 'Is the issue payor mix or procedure mix or volume?' },
  { sector: 'Pharma', typical_margin_range: 'EBITDA 25-35% for innovators, 15-22% for generics', cycle_or_kpi: 'Pipeline value, R&D / sales %, generic erosion rate, patent cliff', cost_drivers: ['R&D (15-20% of sales innovator, 8% generic)', 'Manufacturing', 'Sales force', 'Regulatory'], revenue_drivers: ['New launches', 'Geographic expansion', 'Volume / price', 'Lifecycle management'], recent_disruption: 'Biosimilars, weight-loss GLP-1s reshaping market, AI-discovered drugs', diagnostic_q_for_interviewer: 'What\'s the patent expiry exposure in next 3 years?' },
  { sector: 'Auto / mobility', typical_margin_range: 'EBITDA 8-15% OEM, 12-20% premium, services higher', cycle_or_kpi: 'Volume, ASP, mix (premium/EV), capacity utilization', cost_drivers: ['Raw material (steel, aluminum)', 'Battery (EV)', 'Manufacturing', 'Dealer margins'], revenue_drivers: ['Unit volume', 'ASP / mix', 'After-sales / parts', 'Financing'], recent_disruption: 'EV transition (battery costs, infra), autonomous, software-defined vehicle, mobility-as-service', diagnostic_q_for_interviewer: 'What\'s the EV mix today vs 3-yr-out target?' },
  { sector: 'SaaS / software', typical_margin_range: 'GM 70-85%, mature EBITDA 20-35%, growth-stage net loss', cycle_or_kpi: 'ARR, Net Retention, Gross Retention, CAC payback, Rule of 40', cost_drivers: ['R&D', 'S&M (CAC)', 'Customer success', 'Hosting'], revenue_drivers: ['New ARR', 'Expansion ARR (NRR > 110%)', 'Churn', 'ACV / ARPU'], recent_disruption: 'GenAI commoditizing some categories (writing, support), price compression, vertical AI', diagnostic_q_for_interviewer: 'Is NRR holding up or showing cracks below the surface?' },
  { sector: 'Telecom', typical_margin_range: 'EBITDA 35-45%, FCF much lower due to capex', cycle_or_kpi: 'ARPU, subscriber growth, churn, capex/sales, data usage', cost_drivers: ['Network capex', 'Spectrum costs', 'Customer acquisition', 'Interconnect'], revenue_drivers: ['Subscriber count', 'ARPU (data + voice)', 'Postpaid mix', 'Enterprise / B2B'], recent_disruption: '5G rollout, fiber to home, OTT bundling, mobile money', diagnostic_q_for_interviewer: 'Is ARPU growth from postpaid mix or genuine pricing power?' },
  { sector: 'Energy / oil & gas', typical_margin_range: 'EBITDA 20-35% upstream, 5-10% downstream', cycle_or_kpi: 'Production, reserves life, refining margin, capex/cash flow', cost_drivers: ['Lifting cost', 'Royalties / taxes', 'Refining inputs', 'Logistics'], revenue_drivers: ['Production volume', 'Realized price', 'Product mix', 'Storage / trading'], recent_disruption: 'Energy transition (capex caution), renewables competing, geopolitical price volatility', diagnostic_q_for_interviewer: 'How much of the EBITDA is commodity-price linked vs structural?' },
  { sector: 'Logistics / supply chain', typical_margin_range: 'EBITDA 8-15% asset-light, 15-25% asset-heavy', cycle_or_kpi: 'Cost per shipment, on-time %, fleet utilization, density', cost_drivers: ['Fuel', 'Driver / labor', 'Fleet ownership / lease', 'Last-mile'], revenue_drivers: ['Shipment volume', 'Yield per shipment', 'Network density', 'Service tier mix'], recent_disruption: 'Quick-commerce, drone delivery (limited), automation in warehouses, EV trucks', diagnostic_q_for_interviewer: 'What\'s the fixed-cost leverage if volume grows 20%?' },
  { sector: 'Consumer durables (white goods)', typical_margin_range: 'GM 25-35%, EBITDA 8-14%', cycle_or_kpi: 'Volume, ASP, distribution, replacement cycle', cost_drivers: ['Raw material (steel, copper, plastic)', 'Manufacturing', 'A&P', 'Dealer margins (8-12%)'], revenue_drivers: ['Penetration in lower-tier cities', 'Premium mix', 'Replacement cycle', 'Service revenue'], recent_disruption: 'Smart appliances, e-commerce shifting share from MBOs, financing penetration', diagnostic_q_for_interviewer: 'Is the issue a category problem or company-specific?' },
  { sector: 'Real estate', typical_margin_range: 'EBITDA 25-40% on residential, 50-70% on commercial / annuity', cycle_or_kpi: 'Sales velocity, inventory months, project IRR, rental yield', cost_drivers: ['Land', 'Construction', 'Approval / regulatory', 'Carrying cost'], revenue_drivers: ['Sales velocity', 'Realization per sqft', 'Mix (luxury / affordable)', 'Annuity income'], recent_disruption: 'PropTech (online discovery), REIT structures, flexible workspace, fractional ownership', diagnostic_q_for_interviewer: 'Is the inventory issue demand or pricing?' },
];

// 30 most-asked behavioral questions with STAR scaffolds
export const BEHAVIORAL_30: BehavioralQ[] = [
  { prompt: 'Tell me about a time you led a team through ambiguity.', dimension: 'leadership', star_scaffold: 'S: situation with no clear path. T: had to align team. A: framed problem in pieces, ran fast experiments, communicated daily. R: outcome + what team learned.', spike_move: 'Name the moment you doubted yourself + how you proceeded anyway.', common_mistake: 'Saying "we" not "I" — interviewer wants YOUR action.' },
  { prompt: 'Describe a situation where you had to influence without authority.', dimension: 'leadership', star_scaffold: 'S: needed a cross-functional ask. T: had no formal power. A: built coalition, used data + others\' incentives. R: got buy-in.', spike_move: 'Show how you mapped each stakeholder\'s motivation.', common_mistake: 'Generic "I convinced them" — give the specific argument that worked.' },
  { prompt: 'Give me an example of pushing through a major obstacle.', dimension: 'drive', star_scaffold: 'S: real obstacle (not "I was busy"). T: clear stakes. A: what YOU did including unconventional moves. R: result + what it cost you.', spike_move: 'Acknowledge a moment you wanted to quit + why you didn\'t.', common_mistake: 'Humblebrag obstacles ("I had to work weekends") — pick a real wall.' },
  { prompt: 'Tell me about a time you failed.', dimension: 'growth', star_scaffold: 'S: real failure. T: what you owned. A: what you did wrong. R: what you learned + how you applied it since.', spike_move: 'The lesson must be specific + applied — show the second story.', common_mistake: 'Pseudo-failure ("I\'m too perfectionist") — pick a real one.' },
  { prompt: 'Describe a time you had a serious conflict with a teammate.', dimension: 'connection', star_scaffold: 'S: conflict context. T: relationship at stake. A: how you actually engaged (1-on-1, listened, named the issue). R: resolution + ongoing relationship.', spike_move: 'Show what changed in YOU, not just them.', common_mistake: 'Making the other person sound unreasonable.' },
  { prompt: 'Tell me about a time you took initiative beyond your role.', dimension: 'drive', star_scaffold: 'S: gap you noticed. T: not your job. A: how you stepped in (gracefully, not territorially). R: impact.', spike_move: 'Show that you got buy-in before / during, not retroactive ask-forgiveness.', common_mistake: 'Sounding like a glory-grabber.' },
  { prompt: 'When did you change your mind on something important?', dimension: 'growth', star_scaffold: 'S: held a strong view. T: data / argument that challenged it. A: how you updated (genuinely, not performatively). R: better outcome.', spike_move: 'Name what was uncomfortable about changing your mind.', common_mistake: 'Pretending it was easy — interviewer knows it never is.' },
  { prompt: 'Tell me about the most difficult feedback you\'ve received.', dimension: 'growth', star_scaffold: 'S: setting. T: feedback that landed hard. A: what you did with it (not "I took it well"). R: visible change in subsequent behavior.', spike_move: 'Be specific about what hurt + the work to internalize it.', common_mistake: 'Generic positive framing erases the difficulty.' },
  { prompt: 'Walk me through a project you\'re most proud of.', dimension: 'drive', star_scaffold: 'S: scope + stakes. T: your role. A: what you did + key decisions. R: outcome + why proud.', spike_move: 'The "why proud" should be values-based, not vanity-based.', common_mistake: 'Listing what happened, not what YOU drove.' },
  { prompt: 'Describe a time you delivered under intense time pressure.', dimension: 'resilience', star_scaffold: 'S: deadline + stakes. T: clear deliverable. A: prioritization + cuts you made. R: shipped + cost.', spike_move: 'Be honest about what you cut + how you communicated it.', common_mistake: 'Hero narrative without showing trade-offs.' },
  { prompt: 'Tell me about a time you made an unpopular decision.', dimension: 'leadership', star_scaffold: 'S: context. T: why decision was tough. A: how you decided + communicated. R: outcome + relationship management.', spike_move: 'Show the principle behind the decision, not just the action.', common_mistake: 'Avoiding the unpopularity — interviewer wants the discomfort.' },
  { prompt: 'When did you have to learn something new fast?', dimension: 'curiosity', star_scaffold: 'S: gap. T: deadline. A: how you sourced + learned (not just "I read"). R: applied learning.', spike_move: 'Show the quality of your information diet — who you asked, why them.', common_mistake: 'Saying "I taught myself X in a weekend" — implausible.' },
  { prompt: 'Give me an example of working with a difficult stakeholder.', dimension: 'connection', star_scaffold: 'S: who, why difficult. T: needed their cooperation. A: how you engaged (empathy + clarity). R: result + lesson.', spike_move: 'Acknowledge what was reasonable about their position.', common_mistake: 'Painting them as unreasonable.' },
  { prompt: 'Tell me about a creative solution you came up with.', dimension: 'judgment', star_scaffold: 'S: standard problem. T: standard answer wouldn\'t work. A: the creative move + your reasoning. R: outcome.', spike_move: 'Show why the obvious answer was insufficient.', common_mistake: 'Calling something creative when it was just diligent.' },
  { prompt: 'Describe a data-driven decision you made.', dimension: 'judgment', star_scaffold: 'S: question. T: ambiguous data. A: what data you got, what you concluded, what you ignored. R: decision + outcome.', spike_move: 'Name a piece of data that contradicted your conclusion + how you weighed it.', common_mistake: 'Pretending the data was clean — it never is.' },
  { prompt: 'When did you have to push back on a leader?', dimension: 'leadership', star_scaffold: 'S: leader\'s position. T: you disagreed. A: how you raised it (privately, with evidence). R: leader\'s response + outcome.', spike_move: 'Show you respected their authority while disagreeing.', common_mistake: 'Sounding like you "won" — interviewer wants nuance.' },
  { prompt: 'Tell me about a time you failed to meet expectations.', dimension: 'growth', star_scaffold: 'S: commitment. T: what got in the way. A: how you communicated + recovered. R: changed approach since.', spike_move: 'Own the failure cleanly — no blame.', common_mistake: 'Externalizing — "the team didn\'t deliver".' },
  { prompt: 'Describe how you handled a sudden crisis.', dimension: 'resilience', star_scaffold: 'S: crisis. T: fast call needed. A: what you did first (not what you wanted to do). R: stabilized + lesson.', spike_move: 'The first move is the test — what was it?', common_mistake: 'Telling it as if you weren\'t scared.' },
  { prompt: 'Tell me about a goal you set that was a stretch.', dimension: 'drive', star_scaffold: 'S: starting state. T: ambitious goal + why it scared you. A: plan + adjustments. R: result (don\'t just succeed — show the path).', spike_move: 'Quantify the stretch.', common_mistake: 'Hindsight makes the goal seem smaller — preserve the original tension.' },
  { prompt: 'Walk me through your career decision so far.', dimension: 'curiosity', star_scaffold: 'Through-line: what you optimized for, what you turned down, why current MBA / role.', spike_move: 'Show what you\'ve consciously deprioritized.', common_mistake: 'Listing roles — interviewer wants the WHY between roles.' },
  { prompt: 'Tell me about a time you mentored someone.', dimension: 'connection', star_scaffold: 'S: junior person. T: their growth area. A: how you adapted to them (not your style). R: their growth + what you learned.', spike_move: 'Mentee\'s growth is the real measure, not your effort.', common_mistake: 'Centering yourself in their story.' },
  { prompt: 'Describe a time you simplified something complex.', dimension: 'judgment', star_scaffold: 'S: complex problem. T: needed clarity. A: what you cut + why. R: faster decisions / shipped.', spike_move: 'Name what you LEFT OUT — that\'s the skill.', common_mistake: 'Listing everything you considered — that\'s the opposite of simplification.' },
  { prompt: 'Tell me about an ethical dilemma you faced.', dimension: 'judgment', star_scaffold: 'S: situation with gray. T: principle at stake. A: how you decided + costs. R: outcome + what you\'d do again.', spike_move: 'Pick a real dilemma where reasonable people would disagree.', common_mistake: 'Picking a fake dilemma where the answer was obvious.' },
  { prompt: 'When did you make a mistake under pressure?', dimension: 'growth', star_scaffold: 'S: pressured situation. T: decision point. A: the mistake + what you learned. R: changed approach since.', spike_move: 'Be honest about the pressure that contributed.', common_mistake: 'Pretending you weren\'t at fault.' },
  { prompt: 'Describe a time you built consensus across a divided team.', dimension: 'leadership', star_scaffold: 'S: divide. T: needed alignment. A: surfaced underlying interests, found integrative move. R: alignment + ongoing trust.', spike_move: 'The integrative move is the spike — name it specifically.', common_mistake: 'Sounding like you steamrolled to consensus.' },
  { prompt: 'Tell me about a time you went against the consensus.', dimension: 'judgment', star_scaffold: 'S: group view. T: your contrarian view. A: how you raised it + made the case. R: outcome (works either way — focus on quality of judgment).', spike_move: 'Show the discipline of weighing your conviction vs the room.', common_mistake: 'Self-righteous "I was right" framing.' },
  { prompt: 'Describe a time you turned around an underperformer.', dimension: 'leadership', star_scaffold: 'S: person + gap. T: performance bar. A: diagnostic conversations + adjusted support / role. R: turnaround OR honest exit.', spike_move: 'Sometimes the right answer is helping them leave — show that maturity.', common_mistake: 'Making it sound like coaching alone fixes everything.' },
  { prompt: 'When did you ask for help on something important?', dimension: 'connection', star_scaffold: 'S: stuck. T: real stakes. A: who you asked + how you framed the ask. R: outcome + relationship.', spike_move: 'Asking for help is a strength signal — own it.', common_mistake: 'Being apologetic about needing help.' },
  { prompt: 'Tell me about a time you balanced competing priorities.', dimension: 'judgment', star_scaffold: 'S: priorities A, B, C. T: couldn\'t do all. A: how you weighted + communicated trade-offs. R: outcome.', spike_move: 'Name what you intentionally deprioritized + the cost.', common_mistake: 'Saying you "did it all" — implausible.' },
  { prompt: 'What\'s a strength your manager would name + a weakness?', dimension: 'growth', star_scaffold: 'Strength: real, specific, not generic. Weakness: real (not strength-in-disguise) + how you\'re working on it.', spike_move: 'Weakness should be costly to admit + show concrete work to address.', common_mistake: 'Strength-disguised-as-weakness ("I work too hard").' },
];
