// Strategy / BizOps deep content (hybrid consulting + analytics)

import type { FrameworkDeep, MathDrill, IndustryPrimer } from './tracks-deep';

export const STRATEGY_FRAMEWORKS: FrameworkDeep[] = [
  { name: 'Strategy Diamond (Hambrick & Fredrickson)', when_to_use: 'Strategy formulation', when_NOT_to_use: 'Tactical analytics Qs', structure: ['Arenas (where to compete)', 'Vehicles (how to get there: build/buy/partner)', 'Differentiators', 'Staging (sequencing)', 'Economic logic (how we make money)'], example: 'Spotify: Arenas=audio everywhere, Vehicles=licensing+M&A, Diff=algorithmic discovery, Staging=music→podcasts→audiobooks, Economics=ad-supported→premium funnel.' },
  { name: 'Porter 5 Forces', when_to_use: 'Industry attractiveness', when_NOT_to_use: 'Single-company tactics', structure: ['Buyer power', 'Supplier power', 'New entrants (barriers)', 'Substitutes', 'Rivalry intensity'], example: 'Airline industry: high rivalry, high buyer power (aggregators), low entry barriers (LCC), substitute (rail, video calls), supplier (Boeing/Airbus duopoly).' },
  { name: 'BCG Growth-Share Matrix', when_to_use: 'Portfolio capital allocation', when_NOT_to_use: 'Single-business cases', structure: ['Stars (high share, high growth) — invest', 'Cash cows (high share, low growth) — milk', 'Question marks (low share, high growth) — selective bet', 'Dogs (low share, low growth) — divest'], example: 'Conglomerate: paint=cow, EV=question mark, FMCG=star, telecom=dog.' },
  { name: 'GE-McKinsey 9-box', when_to_use: 'Portfolio with 2 dimensions × 3 levels', when_NOT_to_use: 'Simple 2x2 cases', structure: ['Industry attractiveness (high/med/low)', 'Business strength (high/med/low)', '9-box position → invest/hold/harvest'], example: 'Multi-business co: top-right businesses get capex, bottom-left get divested.' },
  { name: 'Value Chain (Porter)', when_to_use: 'Cost / margin analysis across operations', when_NOT_to_use: 'Pure positioning Qs', structure: ['Inbound logistics', 'Operations', 'Outbound logistics', 'Marketing & sales', 'Service', 'Support: HR, tech, infra, procurement'], example: 'Auto OEM cost: ops 60%, inbound 25%, others <15%. Lever in ops + supplier consolidation.' },
  { name: 'Resource-Based View (RBV)', when_to_use: 'Competitive advantage analysis', when_NOT_to_use: 'External / market Qs', structure: ['Identify resources', 'VRIO test (Valuable, Rare, Inimitable, Organized)', 'Resources passing all 4 = sustainable advantage'], example: 'Apple\'s integration of HW/SW/services + brand + ecosystem = VRIO advantage.' },
  { name: 'Blue Ocean Strategy', when_to_use: 'Greenfield / category creation', when_NOT_to_use: 'Mature competitive markets', structure: ['Identify factors industry competes on', '4 Actions: Eliminate / Reduce / Raise / Create', 'Create new value curve', 'Make competition irrelevant'], example: 'Cirque du Soleil: eliminated animals/stars, reduced humor, raised theatrical, created theme.' },
  { name: 'McKinsey 3 Horizons', when_to_use: 'Innovation portfolio / capital allocation', when_NOT_to_use: 'Single-product Qs', structure: ['H1: defend & extend core (70%)', 'H2: emerging businesses (20%)', 'H3: viable options (10%)'], example: 'Reliance: H1 oil&gas, H2 Jio telecom, H3 GenAI/new energy.' },
  { name: 'Wardley Mapping', when_to_use: 'Mapping value chain across evolution', when_NOT_to_use: 'Static analysis', structure: ['Y axis = visibility to user', 'X axis = evolution (genesis → custom → product → utility)', 'Plot components, identify what to build vs buy'], example: 'Cloud computing: storage utility (commodity), genAI in custom-built phase.' },
  { name: 'Scenario Planning', when_to_use: 'High uncertainty environments', when_NOT_to_use: 'Stable / predictable cases', structure: ['Identify 2 critical uncertainties', '2x2 matrix → 4 scenarios', 'Plan strategy that works across scenarios', 'Identify trigger points / signals'], example: 'EV transition: scenarios = (fast/slow adoption) × (high/low oil price). Robust strategy = invest in EV charging regardless.' },
  { name: 'Make / Buy / Partner', when_to_use: 'Capability acquisition decision', when_NOT_to_use: 'Pure investment Qs', structure: ['Make (build internal): control + IP + slow', 'Buy (acquire): fast + integration risk', 'Partner (alliance): flexible + dependency', 'Decide via: strategic importance × capability gap'], example: 'GenAI capability: high importance + large gap → buy or partner; not make.' },
  { name: 'Issue Tree (Strategic)', when_to_use: 'Diagnose strategic problem', when_NOT_to_use: 'Tactical Qs', structure: ['Top question', 'MECE branches', 'Sub-branches', 'Hypothesis at each leaf'], example: 'Why is competitor gaining share? Internal (product, price, distribution) / External (channel shift, segment shift, regulation).' },
  { name: 'A/B Test Design (BizOps)', when_to_use: 'Validate operational change', when_NOT_to_use: 'Strategic / one-shot decisions', structure: ['Hypothesis (specific, measurable)', 'Primary metric + counter-metric', 'Sample size, power, duration', 'Decision criteria + ramp plan'], example: 'New checkout flow: H = +5% conversion, n=100K, 14 days, ship if p<0.05 + AOV unchanged.' },
  { name: 'Stakeholder Map', when_to_use: 'Change-management / political cases', when_NOT_to_use: 'Pure analytical Qs', structure: ['Influence × Interest 2x2', 'Champions / supporters / fence-sitters / blockers', 'Tailored engagement per quadrant'], example: 'New ERP rollout: CFO=champion, IT head=blocker. Plan = 1:1 with IT to surface concerns.' },
];

export const STRATEGY_MATH: MathDrill[] = [
  { level: 1, name: 'YoY growth', formula: '(this − last) / last', shortcut: 'Common in earnings reports', example: '120 → 144 = 20%', threshold_to_advance: '5 in 30s' },
  { level: 1, name: 'Market share', formula: 'Brand sales / category', shortcut: 'Volume vs value share', example: '$500M / $5B = 10%', threshold_to_advance: 'Volume vs value' },
  { level: 2, name: 'Cohort retention', formula: 'Active users in cohort / cohort size', shortcut: 'D7, M3, M12 typical', example: '1000 cohort, 600 active D30 = 60%', threshold_to_advance: 'Detect cohort improvements' },
  { level: 2, name: 'Statistical significance', formula: 'p < 0.05 with sufficient power', shortcut: 'Need ~16 / (effect size)² × variance for 80% power', example: '5% effect: ~10K per arm', threshold_to_advance: 'Distinguish effect from significance' },
  { level: 2, name: 'Pareto / 80-20', formula: 'Cumulative % of value / cumulative % of items', shortcut: 'Find concentration: 20% of segments often = 80% revenue', example: 'Top 20 of 100 SKUs = 75% of revenue', threshold_to_advance: 'Find inverse Pareto' },
  { level: 3, name: 'Payback period (capital)', formula: 'Investment / annual benefit', shortcut: 'Years to recover', example: '$10M / $2.5M/yr = 4yr', threshold_to_advance: 'Risk-adjusted payback' },
  { level: 3, name: 'NPV', formula: 'Σ CF_t / (1+r)^t − Investment', shortcut: '@10% over 5yr ≈ 3.8× avg CF', example: '$2M/yr 5yr at 10% = $7.6M PV', threshold_to_advance: 'Sensitivity to r' },
  { level: 3, name: 'Hurdle rate', formula: 'WACC + project risk premium', shortcut: 'Strategic projects: 12-15% typical', example: 'Core 9% + risk 5% = 14%', threshold_to_advance: 'Set by project type' },
  { level: 4, name: 'Real options valuation', formula: 'NPV + value of flexibility (Black-Scholes-like)', shortcut: 'Higher uncertainty → higher option value', example: 'Phase 1 trial = option to continue (high σ adds value)', threshold_to_advance: 'Apply to staged decisions' },
];

export const STRATEGY_PRIMERS: IndustryPrimer[] = [
  { sector: 'Tech / SaaS', typical_margin_range: 'GM 70-85%, EBITDA 20-35% mature', cycle_or_kpi: 'ARR, NRR, Rule of 40, magic number', cost_drivers: ['R&D', 'S&M', 'Hosting'], revenue_drivers: ['New ARR', 'Expansion', 'Churn'], recent_disruption: 'GenAI commoditization, vertical AI agents', diagnostic_q_for_interviewer: 'Net retention by cohort?' },
  { sector: 'FMCG', typical_margin_range: 'GM 40-50%, EBITDA 15-25%', cycle_or_kpi: 'Volume growth, distribution, penetration', cost_drivers: ['Raw materials', 'A&P', 'Distribution'], revenue_drivers: ['Distribution width', 'Penetration', 'Mix'], recent_disruption: 'D2C, q-commerce, clean label', diagnostic_q_for_interviewer: 'Volume vs price contribution?' },
  { sector: 'Financial services', typical_margin_range: 'NIM 2.5-4%, ROE 12-18%', cycle_or_kpi: 'NIM, NPA, fee income, deposit growth', cost_drivers: ['Cost of funds', 'Opex', 'Provisioning'], revenue_drivers: ['Loan book', 'NIM', 'Fee income'], recent_disruption: 'Neobanks, embedded finance, GenAI underwriting', diagnostic_q_for_interviewer: 'NPA cycle position?' },
  { sector: 'Healthcare', typical_margin_range: 'EBITDA 18-25%', cycle_or_kpi: 'ARPOB, ALOS, occupancy', cost_drivers: ['Doctor salaries', 'Pharmacy', 'Capex'], revenue_drivers: ['Bed days', 'Procedure mix', 'Payor mix'], recent_disruption: 'Day-care surgery, telemedicine, AI diagnostics', diagnostic_q_for_interviewer: 'Procedure mix shift?' },
];
