// Marketing / Brand / GTM deep content

import type { FrameworkDeep, MathDrill, IndustryPrimer } from './tracks-deep';

export const MKT_FRAMEWORKS: FrameworkDeep[] = [
  { name: '5C-STP-4P (chained)', when_to_use: 'Most marketing cases — the universal chain', when_NOT_to_use: 'Pure metrics analysis', structure: ['5C: Customer / Company / Competition / Collaborators / Context', 'STP: Segment / Target / Position', '4P: Product / Price / Place / Promotion'], example: 'Hippo: 5C reveals health-conscious gap → STP target urban 25-40 health-aware → 4P premium product, +20% pricing, modern trade, digital-first promo.' },
  { name: 'Brand Positioning Canvas', when_to_use: 'Brand strategy / repositioning', when_NOT_to_use: 'Performance marketing', structure: ['Target persona (who specifically)', 'Frame of reference (what category we play in)', 'Point of difference (why us)', 'Reason to believe (proof)'], example: 'Tesla: target=tech-forward affluent, FoR=premium auto, PoD=fastest acceleration + autonomy, RtB=Ludicrous mode + OTA updates.' },
  { name: 'GTM Canvas', when_to_use: 'New product / market launch', when_NOT_to_use: 'Mature brand maintenance', structure: ['ICP (ideal customer profile)', 'Value proposition (job + pain + gain)', 'Channels (where they discover/buy)', 'Pricing & packaging', 'Launch motion (PLG / sales-led / hybrid)', 'Success metrics (90 day, 1 year)'], example: 'B2B SaaS GTM: ICP=200-500 person tech cos, value=replace 3 tools, channels=PLG + outbound, $500/seat/yr, success=$1M ARR Y1.' },
  { name: 'AIDA Funnel', when_to_use: 'Campaign / advertising design', when_NOT_to_use: 'Loyalty / retention Qs', structure: ['Attention (creative hook)', 'Interest (relevant value)', 'Desire (emotional benefit)', 'Action (clear CTA)'], example: 'EV scooter ad: A=range vs ICE, I=fuel savings calc, D=lifestyle imagery, A=test-ride booking.' },
  { name: 'Customer Decision Journey (CDJ)', when_to_use: 'Funnel diagnosis, attribution', when_NOT_to_use: 'Pure metrics analysis', structure: ['Awareness', 'Consideration', 'Evaluation', 'Purchase', 'Post-purchase / loyalty', 'Advocacy (word-of-mouth)'], example: 'EV scooter: drop-off at consideration (range anxiety). Fix = experience centers + range simulator.' },
  { name: 'Ansoff Matrix (Growth)', when_to_use: 'Growth strategy', when_NOT_to_use: 'Cost / operational Qs', structure: ['Market penetration (existing × existing)', 'Product development (new × existing market)', 'Market development (existing product × new market)', 'Diversification (new × new) — riskiest'], example: 'Hindustan Unilever: penetration=lower-tier cities, dev=clean-label SKUs, market dev=Africa, diversify=avoid.' },
  { name: 'Brand Equity Model (Aaker / Keller)', when_to_use: 'Brand health diagnosis', when_NOT_to_use: 'Tactical campaign', structure: ['Brand awareness', 'Brand associations (attributes, benefits, attitudes)', 'Perceived quality', 'Brand loyalty'], example: 'Coke: awareness 100%, association=happiness/refreshment, quality=consistent, loyalty=repeat purchase 80%.' },
  { name: 'Loyalty Ladder', when_to_use: 'CRM / retention strategy', when_NOT_to_use: 'Acquisition Qs', structure: ['Suspect → Prospect → Customer → Client → Advocate → Partner', 'Each level has different unlock criteria + value'], example: 'Sephora Beauty Insider: tier-based, Rouge spend $1K+/yr unlocks events + early access.' },
  { name: 'Pricing Strategy Tree', when_to_use: 'Pricing decisions', when_NOT_to_use: 'Cost-out cases', structure: ['Cost-based (cost + margin) — floor', 'Competitor-based (vs alternatives) — ceiling', 'Value-based (willingness to pay × % capture) — true price', 'Penetration vs Skim', 'Bundling / unbundling', 'Dynamic / personalized'], example: 'Drug for rare disease: value-based pricing ($60K/yr) >> competitor or cost-based.' },
  { name: '7Ps (Service marketing)', when_to_use: 'Service brands', when_NOT_to_use: 'Pure goods', structure: ['Product (core service + augmented)', 'Price', 'Place', 'Promotion', 'People (employees who deliver)', 'Process (service delivery flow)', 'Physical evidence (tangibles)'], example: 'Hospital chain: product=outcomes, people=star doctors, process=appointment-to-discharge experience.' },
  { name: 'McKinsey 3 Horizons (innovation)', when_to_use: 'Portfolio of bets', when_NOT_to_use: 'Single-product Qs', structure: ['H1: defend & extend core (70% resources)', 'H2: build emerging businesses (20%)', 'H3: create viable options (10%)'], example: 'Reliance: H1=oil&gas, H2=Jio telecom, H3=GenAI / new energy.' },
  { name: 'Net Promoter Score (NPS) framework', when_to_use: 'CX / loyalty diagnosis', when_NOT_to_use: 'Pure performance metrics', structure: ['Promoters (9-10) − Detractors (0-6) = NPS', 'Segment by journey stage', 'Root-cause low ratings → fix systematically'], example: 'Hotel: NPS 30 (decent). Detractors complain about wifi. Fix = $50K capex, NPS 50.' },
  { name: 'Pricing Elasticity Decision', when_to_use: 'Price increase / decrease decision', when_NOT_to_use: 'New-product pricing', structure: ['Estimate elasticity (historical or test)', '|E| > 1 = elastic (raise hurts revenue)', 'Segment by customer type', 'Use price discrimination if possible'], example: 'Streaming service: business users elastic (cancel), home users inelastic. Raise prices for home only.' },
  { name: 'Brand Architecture', when_to_use: 'Multi-brand portfolio decisions', when_NOT_to_use: 'Single-brand cases', structure: ['Branded house (Apple — one master brand)', 'House of brands (P&G — distinct brands)', 'Endorsed brands (Marriott Marquis — sub-brand with parent)', 'Hybrid'], example: 'P&G house of brands: Tide ≠ Pampers ≠ Gillette, each owning different jobs.' },
  { name: 'Promotion Mix', when_to_use: 'Campaign budget allocation', when_NOT_to_use: 'Pricing / product Qs', structure: ['Advertising (mass)', 'Sales promotion (short-term incentive)', 'PR (earned media)', 'Direct marketing (1-to-1)', 'Personal selling', 'Digital / content (own channels)'], example: 'New EV: 40% digital, 25% PR (launch event), 20% trade promo, 15% TV/OOH.' },
  { name: 'STEEP / PESTEL (Macro)', when_to_use: 'Macro environmental scan', when_NOT_to_use: 'Tactical brand Qs', structure: ['Social (demographics, attitudes)', 'Technological', 'Economic', 'Environmental', 'Political'], example: 'Auto sector: S=urbanization, T=EV+autonomy, E=interest rates, En=climate mandates, P=subsidy policy.' },
];

export const MKT_MATH: MathDrill[] = [
  { level: 1, name: 'CAC', formula: 'Marketing spend / new customers acquired', shortcut: 'By channel, by cohort', example: '$1M / 5K = $200 CAC', threshold_to_advance: 'Distinguish blended vs paid' },
  { level: 1, name: 'ROAS', formula: 'Revenue / Ad spend', shortcut: 'Target ≥3x for sustainable growth', example: '$300K rev / $100K spend = 3x', threshold_to_advance: 'Connect to LTV/CAC' },
  { level: 1, name: 'Market share', formula: 'Brand sales / total category sales', shortcut: 'Volume share vs value share differ', example: '$500M brand / $5B category = 10%', threshold_to_advance: 'Volume vs value distinction' },
  { level: 1, name: 'GRP / TRP (advertising)', formula: 'Reach × Frequency', shortcut: 'GRP = total exposures / 100', example: '40% reach × 3 freq = 120 GRPs', threshold_to_advance: 'Convert to spend efficiency' },
  { level: 2, name: 'LTV', formula: 'ARPU × gross margin × avg lifetime', shortcut: '1 / churn rate gives lifetime in same period', example: 'ARPU $50, GM 60%, churn 5%/mo → LTV $600', threshold_to_advance: 'Adjust for retention curve' },
  { level: 2, name: 'CAC payback', formula: 'CAC / monthly contribution margin', shortcut: '<12mo healthy for B2C, <24mo B2B', example: 'CAC $200 / $20/mo = 10mo', threshold_to_advance: 'Connect to growth rate' },
  { level: 2, name: 'CPM (cost per mille)', formula: 'Cost / impressions × 1000', shortcut: 'TV ~$15-30, social ~$5-15, programmatic ~$1-5', example: '$5K spend / 500K imp × 1000 = $10 CPM', threshold_to_advance: 'Compare across channels' },
  { level: 2, name: 'CPC / CTR', formula: 'CPC = spend / clicks; CTR = clicks / impressions', shortcut: 'Search 1-3% CTR healthy, display 0.05-0.1%', example: '$1 CPC × 50K clicks = $50K spend; 50K/2M = 2.5% CTR', threshold_to_advance: 'Link CPC × Conv → CAC' },
  { level: 2, name: 'Conversion rate', formula: 'Conversions / clicks (or visits)', shortcut: 'E-commerce 1-3%, B2B SaaS lead form 5-10%', example: '500 buys / 50K clicks = 1%', threshold_to_advance: 'Multi-step funnel' },
  { level: 3, name: 'Marketing payback period', formula: 'CAC / contribution margin per period', shortcut: 'Monthly recurring → quick payback', example: 'B2B SaaS CAC $5K / $300/mo CM = 17mo', threshold_to_advance: 'Sensitivity to churn' },
  { level: 3, name: 'NPV of customer', formula: 'Σ (CF_t × M_t) / (1+r)^t', shortcut: 'PV of contribution × retention curve', example: 'Yr1 $200, Yr2 $180 (M=0.9), Yr3 $150 → NPV $480', threshold_to_advance: 'Compute lifetime' },
  { level: 3, name: 'Brand premium', formula: '(Branded price − Generic price) / Generic price', shortcut: 'Test of brand strength', example: 'Branded $5 vs generic $3 → 67% premium', threshold_to_advance: 'Translate to gross margin' },
  { level: 3, name: 'Marketing ROI (MROI)', formula: '(Incremental margin − marketing cost) / marketing cost', shortcut: 'Use incrementality, not attribution', example: '$10M incr margin from $3M spend → 233% MROI', threshold_to_advance: 'Run holdout test for incrementality' },
  { level: 4, name: 'Media mix model (MMM) coefficients', formula: 'Linear regression: Sales = β1×TV + β2×Digital + ... + ε', shortcut: 'Use saturation curves + adstock', example: 'Digital β = 0.4 → +$1M digital → +$400K incremental sales', threshold_to_advance: 'Interpret coefficients' },
  { level: 4, name: 'Customer Equity (Rust et al)', formula: 'Σ LTV across all customer cohorts', shortcut: 'Total brand value driven by relationships', example: '10K customers × $600 LTV = $6M customer equity', threshold_to_advance: 'Compare across competitors' },
];

export const MKT_INDUSTRY_PRIMERS: IndustryPrimer[] = [
  { sector: 'FMCG', typical_margin_range: 'GM 40-50%, EBITDA 15-25%', cycle_or_kpi: 'Volume growth, distribution width, penetration, premium mix', cost_drivers: ['A&P 10-15% of sales', 'Trade margins 10-20%', 'Raw materials (commodity)'], revenue_drivers: ['Distribution', 'Penetration', 'Per-cap consumption', 'Premiumization'], recent_disruption: 'D2C eating share, quick-commerce, clean-label trend', diagnostic_q_for_interviewer: 'Volume vs price contribution to growth?' },
  { sector: 'Retail / e-commerce', typical_margin_range: 'GM 25-40%, EBITDA 5-10%', cycle_or_kpi: 'GMV, AOV, repeat rate, take rate', cost_drivers: ['Logistics & fulfillment', 'Marketing CAC', 'Returns'], revenue_drivers: ['Customer count', 'Order frequency', 'AOV'], recent_disruption: 'Quick-commerce, live commerce, AI search', diagnostic_q_for_interviewer: 'Cohort retention trend?' },
  { sector: 'Quick-commerce / d2c', typical_margin_range: 'GM 20-30%, EBITDA −5 to 5% (often loss)', cycle_or_kpi: 'Order frequency, AOV, dark-store density, cohort contribution', cost_drivers: ['Marketing CAC', 'Last-mile delivery', 'Dark-store opex', 'Discounts/cashbacks'], revenue_drivers: ['Frequency', 'AOV', 'Geographic expansion'], recent_disruption: 'Q-commerce convergence, embedded finance offers', diagnostic_q_for_interviewer: 'Path to contribution-margin positive per dark store?' },
  { sector: 'Auto / mobility', typical_margin_range: 'EBITDA 8-15% OEM, 12-20% premium', cycle_or_kpi: 'Volume, ASP, premium/EV mix, dealer network', cost_drivers: ['Raw material', 'Battery (EV)', 'Dealer margins'], revenue_drivers: ['Volume', 'ASP / mix', 'After-sales'], recent_disruption: 'EV transition, software-defined vehicle, mobility-as-service', diagnostic_q_for_interviewer: 'EV mix today vs 3-yr target?' },
  { sector: 'EdTech / edutainment', typical_margin_range: 'GM 50-70%, EBITDA loss-making in growth phase', cycle_or_kpi: 'Enrollment, completion, NPS, CAC', cost_drivers: ['CAC (very high)', 'Content/teachers', 'Tech'], revenue_drivers: ['Enrollments', 'Course price', 'Renewal'], recent_disruption: 'GenAI tutors, micro-credentials, free abundance', diagnostic_q_for_interviewer: 'LTV/CAC by channel + completion rate?' },
  { sector: 'Beauty / personal care', typical_margin_range: 'GM 60-75%, EBITDA 15-25%', cycle_or_kpi: 'New launches share, e-commerce penetration, repeat rate', cost_drivers: ['A&P (15-20% of sales)', 'COGS', 'Trade'], revenue_drivers: ['Premium mix', 'New launches', 'D2C share'], recent_disruption: 'D2C clean-label brands, social-commerce, GenAI personalization', diagnostic_q_for_interviewer: 'New-launch contribution to growth?' },
];
