// IB / PE / VC deep content

import type { FrameworkDeep, MathDrill, IndustryPrimer } from './tracks-deep';

export const IB_FRAMEWORKS: FrameworkDeep[] = [
  { name: 'DCF (Discounted Cash Flow)', when_to_use: 'Intrinsic valuation when 5-10yr forecast is plausible', when_NOT_to_use: 'Early-stage / negative-cashflow companies — use VC method or comps', structure: ['Project unlevered FCF (5-10yr)', 'Terminal value (Gordon growth or Exit Multiple)', 'Discount at WACC', 'Sum to get Enterprise Value', 'EV − Debt + Cash = Equity Value'], example: 'Mature SaaS — 8-yr forecast at 25% then 3% terminal, WACC 10%, EBITDA exit at 20x. EV = 12B.' },
  { name: 'Paper LBO', when_to_use: 'PE buyout — quick mental math for IRR / MOIC', when_NOT_to_use: 'When you have time for a real model', structure: ['Entry: EBITDA × multiple − net debt = equity check', 'Project FCF + debt paydown over hold (5yr)', 'Exit: Yr5 EBITDA × exit multiple − remaining debt', 'IRR = (Exit equity / Entry equity)^(1/5) − 1', 'MOIC = Exit equity / Entry equity'], example: '$100M EBITDA × 8 − $500M debt = $300M equity check. 5yr later $150M × 9 − $200M debt = $1.15B equity. MOIC 3.8x, IRR ~30%.' },
  { name: 'Comparable Companies (trading comps)', when_to_use: 'Relative valuation, sanity check on DCF', when_NOT_to_use: 'No public peers / unique business', structure: ['Identify 5-7 peers (similar size, geo, business)', 'Pull EV/EBITDA, EV/Revenue, P/E', 'Adjust for growth / margin differential', 'Apply median multiple to target metric'], example: 'EV/EBITDA peers 12-18x, target growing faster → 16x × $50M = $800M EV.' },
  { name: 'Precedent Transactions (deal comps)', when_to_use: 'M&A pricing benchmark', when_NOT_to_use: 'Going-concern valuation (use trading comps)', structure: ['Find recent M&A in sector (last 3-5yr)', 'Compute deal multiples (EV/EBITDA, EV/Sales)', 'Adjust for control premium (20-30%)', 'Apply to target'], example: 'Recent SaaS M&A at 8-12x revenue, premium of 25%. Target value 10x.' },
  { name: 'Accretion / Dilution', when_to_use: 'M&A EPS impact analysis', when_NOT_to_use: 'Strategic rationale (use NPV / synergies)', structure: ['Combined Net Income (acquirer + target − interest on new debt)', 'New share count (existing + shares issued)', 'New EPS = Combined NI / new shares', 'Compare to standalone EPS'], example: 'Standalone EPS $5. Acquire target adds $200M NI, $50M interest. Issue 30M shares (already 200M). New EPS = (1B + 150M) / 230M = $5. Neutral.' },
  { name: 'LBO (full model)', when_to_use: 'PE underwriting deep-dive', when_NOT_to_use: 'First-pass screening (use paper LBO)', structure: ['Source/uses of funds at close', '5yr operating model', 'Debt schedule with cash sweep', 'Returns sensitivity to entry/exit multiples + leverage'], example: '5x debt + 4x equity at entry, 2x leverage at exit, 3.5x MOIC at base case.' },
  { name: 'Sum-of-the-parts (SOTP)', when_to_use: 'Conglomerate, multi-segment business', when_NOT_to_use: 'Single-business pure-play', structure: ['Value each segment separately (peers + multiples)', 'Sum segment values', 'Subtract holding-co costs', 'Compare to current EV (look for unlock)'], example: 'Reliance: telecom 8x, retail 12x, oil 4x, digital 25x → SOTP 30% above market.' },
  { name: 'Three-statement linkage', when_to_use: 'Modeling / technical interview', when_NOT_to_use: 'Strategy questions', structure: ['IS: Revenue → EBIT → Net Income', 'BS: Assets = Liab + Equity (NI flows to RE)', 'CF: NI + non-cash + ΔWC + capex + financing → end cash → BS cash'], example: 'Depreciation: hits IS (−), CF (+ in operating), BS (− asset).' },
  { name: 'WACC build', when_to_use: 'Discount rate for DCF', when_NOT_to_use: 'Adjusted Present Value (use unlevered cost of equity)', structure: ['Cost of equity (CAPM: Rf + β × ERP)', 'Cost of debt (after-tax: Rd × (1−T))', 'Weights (E/V, D/V at market)', 'Weighted average'], example: 'Rf 4%, β 1.2, ERP 6% → Re 11.2%. Rd 5% × 0.7 = 3.5%. 70% E + 30% D → WACC 8.9%.' },
  { name: 'Football field (valuation summary)', when_to_use: 'Pitch / fairness opinion', when_NOT_to_use: 'Single-method analysis', structure: ['DCF range (low → high)', 'Trading comps range', 'Precedent transactions range', '52-wk high/low', 'Premium analysis', 'Plot all on one chart'], example: 'Football field shows $40-60/sh range, current $45. Bid at $55 (top quartile).' },
  { name: 'Brain teaser approach', when_to_use: 'Mental math / quick logic Qs in interview', when_NOT_to_use: 'Real cases', structure: ['Restate the question', 'Identify the trick / unstated assumption', 'Decompose into clean numbers', 'Solve + sanity check'], example: 'How many golf balls fit in a 747? Volume of plane / volume of ball × packing efficiency ≈ 30M.' },
  { name: 'Dividend recap', when_to_use: 'PE liquidity event without exit', when_NOT_to_use: 'Companies with no debt capacity', structure: ['Re-leverage to target debt level', 'Use proceeds to pay div to PE', 'IRR boost', 'Risk: leaves company more leveraged'], example: '$1B EBITDA, 4x debt → 5x debt: $1B dividend out without changing ownership.' },
  { name: 'Restructuring waterfall', when_to_use: 'Distressed / bankruptcy', when_NOT_to_use: 'Going concern', structure: ['Senior secured (paid first)', 'Senior unsecured', 'Subordinated', 'Preferred', 'Common (last)'], example: 'EV $500M, senior debt $400M (100% recovery), unsecured $300M (33% recovery), equity zero.' },
  { name: 'Synergy quantification', when_to_use: 'M&A pre-deal', when_NOT_to_use: 'Distressed / cost-cuts only', structure: ['Revenue synergies (cross-sell, pricing, channel) — typically discounted heavily', 'Cost synergies (overlapping HQ, procurement, ops) — easier to realize', 'Run-rate vs achieved (apply realization curve)', 'Tax-affected, NPV the stream'], example: '$200M cost synergy YR3, 80% realization → $160M run-rate. NPV at 10% / 5x = $800M.' },
  { name: 'M&A deal types', when_to_use: 'Categorizing the transaction', when_NOT_to_use: 'Pure valuation', structure: ['Strategic (industrial buyer, synergy story)', 'Financial (PE, IRR-driven)', 'Reverse merger (private into shell)', 'Tender offer / hostile', 'Take-private', 'JV / strategic stake'], example: 'PE bidding $X, strategic at $X+15% (synergies justify premium).' },
  { name: 'Exit multiple sensitivity', when_to_use: 'PE returns analysis', when_NOT_to_use: 'Public-comp valuation', structure: ['Run IRR table at exit multiples 6x / 8x / 10x', 'Show sensitivity to debt paydown', 'Identify break-even exit multiple'], example: 'Base case 8x → 22% IRR. Need >5x exit just to break even.' },
  { name: 'Capital structure decision', when_to_use: 'Refinancing, debt issuance', when_NOT_to_use: 'Operational cases', structure: ['Coverage ratios (Debt/EBITDA, EBITDA/Interest)', 'Cost of capital implications', 'Covenant headroom', 'Rating impact'], example: 'Take leverage from 3x to 5x: ratings drop 2 notches, cost of debt up 200bps but tax shield gains.' },
];

export const IB_MATH: MathDrill[] = [
  { level: 1, name: 'EV bridge', formula: 'EV = Equity + Debt − Cash', shortcut: 'EV is what acquirer pays in full', example: 'Equity $500M, debt $200M, cash $50M → EV $650M', threshold_to_advance: 'Move EV ↔ Equity 5 times' },
  { level: 1, name: 'EBITDA reconciliation', formula: 'NI + Tax + Interest + D&A', shortcut: 'Reverse from IS bottom up', example: 'NI $100, Tax $30, Int $20, D&A $50 → EBITDA $200', threshold_to_advance: 'From cash flow statement directly' },
  { level: 2, name: 'WACC', formula: '(E/V × Re) + (D/V × Rd × (1−T))', shortcut: 'CAPM for Re; after-tax for Rd', example: '70% E at 12% + 30% D at 6%(0.7) = 8.4 + 1.26 = 9.66%', threshold_to_advance: 'Solve with given inputs in 30s' },
  { level: 2, name: 'CAPM', formula: 'Rf + β × ERP', shortcut: 'Rf ≈ 10yr treasury, ERP ≈ 5-7%', example: 'Rf 4%, β 1.2, ERP 6% → 11.2%', threshold_to_advance: 'Reverse-engineer β from Re' },
  { level: 2, name: 'Terminal value (Gordon)', formula: 'FCF × (1+g) / (WACC − g)', shortcut: '~10× FCF if g=3%, WACC=11%', example: 'FCF=10, g=3%, WACC=11% → 10×1.03/0.08 = 128.75', threshold_to_advance: 'Sensitivity to g' },
  { level: 2, name: 'Terminal value (Exit Multiple)', formula: 'Yr-N EBITDA × Exit multiple', shortcut: 'Use trading comp multiple, slight discount', example: '$50M × 9x = $450M', threshold_to_advance: 'Match trading comp methodology' },
  { level: 3, name: 'IRR (paper)', formula: '(Exit / Entry)^(1/n) − 1', shortcut: '2x in 5yr ≈ 15%, 3x ≈ 25%, 4x ≈ 32%', example: '$300M → $1.2B in 5yr → 32%', threshold_to_advance: 'Mental math in 10s' },
  { level: 3, name: 'MOIC', formula: 'Exit equity / Entry equity', shortcut: 'Target 2-3x in 5yr for buyout', example: '$300 → $900 = 3x MOIC', threshold_to_advance: 'Connect MOIC ↔ IRR' },
  { level: 3, name: 'Levered FCF', formula: 'NI + D&A − ΔWC − Capex', shortcut: 'Cash to equity holders', example: 'NI 100 + D&A 50 − WC 20 − Capex 60 = 70', threshold_to_advance: 'Connect to dividend capacity' },
  { level: 3, name: 'Unlevered FCF', formula: 'EBIT × (1−T) + D&A − ΔWC − Capex', shortcut: 'EBIT(1-T) is the starting point', example: 'EBIT 200 × 0.7 + D&A 50 − 20 − 60 = 110', threshold_to_advance: 'Use for DCF discounting' },
  { level: 3, name: 'DSCR (debt service coverage)', formula: 'EBITDA / (Interest + Principal)', shortcut: 'Lender covenant typically >1.2x', example: 'EBITDA $80, debt service $50 → DSCR 1.6x', threshold_to_advance: 'Identify covenant breach scenarios' },
  { level: 3, name: 'Net Debt / EBITDA', formula: '(Debt − Cash) / EBITDA', shortcut: 'Standard leverage metric', example: 'Net debt $400M / EBITDA $100M = 4.0x', threshold_to_advance: 'Connect to credit rating' },
  { level: 4, name: 'Accretion / Dilution math', formula: 'New EPS vs Old EPS, factor in synergies + deal financing', shortcut: 'Accretive if target P/E < acquirer P/E (after-tax cost of debt)', example: 'Stock-for-stock at premium → typically dilutive Y1, accretive Y3 with synergies', threshold_to_advance: 'Compute Y1 vs run-rate' },
  { level: 4, name: 'NPV with mid-year convention', formula: 'CF / (1+r)^(t-0.5)', shortcut: 'Add 0.5yr to denominator', example: 'CF in Yr1 = CF / 1.1^0.5 = CF / 1.049', threshold_to_advance: 'Compare end-of-year vs mid-year impact' },
  { level: 4, name: 'Stub period (DCF)', formula: 'CF × (months remaining / 12) discounted', shortcut: 'Adjust for partial first year', example: '7 months remaining of Yr1 → CF × 7/12 / 1.1^(7/12)', threshold_to_advance: 'Match published valuations' },
  { level: 4, name: 'Tax shield value', formula: 'Debt × Tax rate × Cost of debt × (annuity factor)', shortcut: 'PV of perpetual tax shield = Debt × Tax rate', example: '$1B × 25% = $250M permanent tax shield NPV', threshold_to_advance: 'APV decomposition' },
];

export const IB_INDUSTRY_PRIMERS: IndustryPrimer[] = [
  { sector: 'Banking', typical_margin_range: 'NIM 2.5-4%, ROE 12-18%', cycle_or_kpi: 'NIM, cost-to-income, NPA, deposit growth, fee income', cost_drivers: ['Cost of funds (deposits)', 'Operating expenses (branches, tech)', 'Provisioning'], revenue_drivers: ['Loan book growth', 'NIM', 'Fee income', 'Cross-sell'], recent_disruption: 'Neobanks (fee compression), UPI (zero MDR), embedded finance', diagnostic_q_for_interviewer: 'What\'s the cost-of-funds outlook + NPA cycle?' },
  { sector: 'Insurance', typical_margin_range: 'Combined ratio <100% = profit; equity float drives investment income', cycle_or_kpi: 'Combined ratio, persistency, GWP growth, AUM yield', cost_drivers: ['Claims', 'Acquisition costs', 'Operating'], revenue_drivers: ['Premium volume', 'Pricing', 'Investment income on float'], recent_disruption: 'Direct-to-consumer (Lemonade), parametric insurance, climate risk repricing', diagnostic_q_for_interviewer: 'Combined ratio trend + investment yield?' },
  { sector: 'Asset Management', typical_margin_range: 'EBITDA 30-45%, fee-based', cycle_or_kpi: 'AUM, net flows, fee rate, performance', cost_drivers: ['Compensation (50%+)', 'Distribution', 'Tech / data'], revenue_drivers: ['Net inflows', 'Markets (β)', 'Performance fees', 'Mix shift to alts'], recent_disruption: 'Passive (Vanguard), private credit boom, GenAI for research', diagnostic_q_for_interviewer: 'Active vs passive split, alts %?' },
  { sector: 'Oil & Gas (E&P)', typical_margin_range: 'EBITDA 30-50% upstream, 5-15% downstream', cycle_or_kpi: 'Production, reserves life, lifting cost, capex/cash flow', cost_drivers: ['Lifting cost', 'Royalties / taxes', 'Capex'], revenue_drivers: ['Production volume', 'Realized price (commodity-linked)', 'Hedge book'], recent_disruption: 'Energy transition / capex caution, ESG pressure on capital', diagnostic_q_for_interviewer: 'Hedge book + breakeven oil price?' },
  { sector: 'Infrastructure / Utilities', typical_margin_range: 'EBITDA 50-70% on regulated assets, FCF lower due to capex', cycle_or_kpi: 'RAB (regulated asset base), allowed return, availability factor', cost_drivers: ['Maintenance capex', 'Fuel (in non-renewables)'], revenue_drivers: ['Tariff increase', 'Demand growth', 'New asset additions'], recent_disruption: 'Renewable transition, smart grids, EV charging integration', diagnostic_q_for_interviewer: 'Allowed RoE vs achieved?' },
  { sector: 'Real Estate / REITs', typical_margin_range: 'EBITDA 60-75% on rental assets, lower on residential dev', cycle_or_kpi: 'NOI, occupancy, rental growth, cap rate', cost_drivers: ['Property opex', 'Maintenance capex', 'Interest cost (high leverage)'], revenue_drivers: ['Rent escalation', 'Occupancy', 'Acquisition activity'], recent_disruption: 'Office demand softness post-WFH, data center boom, last-mile logistics premium', diagnostic_q_for_interviewer: 'Lease maturity profile + cap rate trend?' },
];
