// Second-pass orchestrator. Targets PDFs that the first pass parse-skipped
// (one big chunk, no Case-N headers). For each, slabifies the text and asks
// DeepSeek V4 to extract every case it finds, then dedupes by (casebook, title)
// and inserts.

import { parsePdfFile } from './parse';
import { extractMultiCases, slabify } from './extract-multi';
import { upsertCasebook, insertCase, bumpCasebookCount } from './insert';
import { Throttle } from './throttle';
import { log } from './log';
import path from 'path';
import { readdir, readFile, stat } from 'fs/promises';
import { pathToFileURL } from 'url';

const llmThrottle = new Throttle(35, 60_000);
const CONCURRENCY = Number(process.env.INGEST_CONCURRENCY) || 4;

const RAW_DIR = path.resolve(process.cwd(), 'casebooks/raw');

async function targets(): Promise<{ school: string; localPath: string; pdfUrl: string }[]> {
  let entries: string[];
  try { entries = await readdir(RAW_DIR); } catch { return []; }
  const out = [];
  for (const name of entries) {
    if (!name.toLowerCase().endsWith('.pdf')) continue;
    const localPath = path.join(RAW_DIR, name);
    const sepIdx = name.indexOf('__');
    const school = sepIdx > 0 ? name.slice(0, sepIdx) : 'manual';
    out.push({ school, localPath, pdfUrl: pathToFileURL(localPath).href });
  }
  return out;
}

async function main() {
  await log('info', 'second-pass', `start (CONCURRENCY=${CONCURRENCY})`);
  const list = await targets();

  let totalSlabs = 0;
  let totalInserted = 0;
  let totalSkippedDup = 0;

  for (const t of list) {
    const fname = path.basename(t.localPath);
    let textBlob: string;

    // Prefer OCR'd text when available (for scanned PDFs that direct parsing
    // can't read). casebooks/ocr/<name>.txt is generated by ocr-scanned.py.
    const ocrPath = path.resolve('casebooks/ocr', fname.replace(/\.pdf$/, '.txt'));
    let usedOcr = false;
    try {
      const s = await stat(ocrPath);
      if (s.size > 1000) {
        textBlob = await readFile(ocrPath, 'utf-8');
        usedOcr = true;
      } else {
        throw new Error('ocr file too small');
      }
    } catch {
      try {
        const parsed = await parsePdfFile(t.localPath);
        textBlob = parsed.text;
      } catch (e) {
        await log('error', 'second-pass', `parse fail ${fname}: ${(e as Error).message.slice(0, 200)}`);
        continue;
      }
    }

    if (textBlob.length < 1000) {
      await log('info', 'second-pass', `skip ${fname} (text too short, scanned PDF without OCR — run ocr-scanned.py)`);
      continue;
    }

    const slabs = slabify(textBlob);
    await log('info', 'second-pass', `${fname} → ${slabs.length} slabs (${(textBlob.length / 1000).toFixed(0)}kc text${usedOcr ? ', OCR' : ''})`);

    const casebookId = await upsertCasebook(t.school, null, fname.replace(/\.pdf$/, ''), t.pdfUrl, t.localPath);

    let bookInserted = 0;
    let bookDup = 0;
    let bookSlabs = 0;
    let next = 0;

    const worker = async () => {
      while (true) {
        const i = next++;
        if (i >= slabs.length) return;
        const slab = slabs[i];
        await llmThrottle.acquire();
        let cases: any[] = [];
        try {
          cases = await extractMultiCases(slab);
        } catch (e) {
          await log('warn', 'second-pass', `slab ${i} of ${fname} failed: ${(e as Error).message.slice(0, 200)}`);
          continue;
        }
        bookSlabs++;
        for (const c of cases) {
          if (!c?.title || !c?.problem_statement) continue;
          const r = await insertCase({
            title: c.title,
            industry: c.industry || 'other',
            case_type: c.case_type || 'other',
            difficulty: c.difficulty || 'medium',
            source: c.source ?? t.school,
            casebook_id: casebookId,
            problem_statement: c.problem_statement,
            interviewer_notes: c.interviewer_notes ?? [],
            ideal_structure: c.ideal_structure ?? {},
            tags: c.tags ?? [],
            provenance: { school: t.school, casebook_title: fname, source_url: t.pdfUrl, pass: 'second' },
          });
          if (r.inserted) bookInserted++; else bookDup++;
        }
      }
    };

    await Promise.all(Array.from({ length: CONCURRENCY }, () => worker()));
    if (bookInserted > 0) await bumpCasebookCount(casebookId, bookInserted);
    await log('info', 'second-pass', `${fname} → ${bookInserted} inserted, ${bookDup} dup, ${bookSlabs}/${slabs.length} slabs ok`);
    totalSlabs += bookSlabs;
    totalInserted += bookInserted;
    totalSkippedDup += bookDup;
  }

  await log('info', 'second-pass', `done. inserted=${totalInserted} dup=${totalSkippedDup} slabs=${totalSlabs}`);
}

main().catch((err) => { console.error(err); process.exit(1); });
